Embedded Systems Library: EEPROM Public Functions
EEPROM Public Functions
EEPROM
Macros
#define EEPROM_PAGE_LENGTH 32
Max length (in bytes) of a single page to write to EEPROM.
#define EEPROM_ADDRESS 0x50
EEPROM address.
#define EEPROM_FREQUENCY 400000
EEPROM operating frequency.
Functions
void EEPROM_Init ()
int EEPROM_Read (char *buffer, int size)
int EEPROM_Write (char *buffer, int size)
Detailed Description
Macro Definition Documentation
EEPROM_ADDRESS
#define EEPROM_ADDRESS 0x50
EEPROM address.
Definition at line 39 of file eeprom.h.
EEPROM_FREQUENCY
#define EEPROM_FREQUENCY 400000
EEPROM operating frequency.
Definition at line 44 of file eeprom.h.
EEPROM_PAGE_LENGTH
#define EEPROM_PAGE_LENGTH 32
Max length (in bytes) of a single page to write to EEPROM.
Definition at line 34 of file eeprom.h.
Function Documentation
EEPROM_Init()
void EEPROM_Init ()
Definition at line 10 of file eeprom.c.
References I2C1_Init().
EEPROM_Read()
int EEPROM_Read (char * buffer, int size)
Definition at line 14 of file eeprom.c.
References EEPROM_ADDRESS, EEPROM_FREQUENCY, I2C1_Configure(), I2C1_Engine(), I2C1_GetBuffer(), I2C1_Start(), and I2C1_Stop().
EEPROM_Write()
int EEPROM_Write (char * buffer, int size)
Definition at line 24 of file eeprom.c.
References EEPROM_ADDRESS, EEPROM_FREQUENCY, EEPROM_PAGE_LENGTH, I2C1_Configure(), I2C1_Engine(), I2C1_Start(), I2C1_Stop(), and WAIT_SYS_Ms().