Embedded Systems Library: BUTTON Public Functions
BUTTON Public Functions
BUTTON
Macros
#define DEBOUNCE_TIME 50
Debounce time.
#define BUTTONS_MASK (B1 | B2 | B3)
Mask for all 3 buttons.
Enumerations
enum BUTTON { B1 = (1 << 1), B2 = (1 << 2), B3 = (1 << 3) }
Input buttons.
Functions
void BUTTON_Init (void)
Initialises the button API.
int32_t BUTTON_Hit (void)
Gets input buttons bitmap.
int32_t BUTTON_Read (void)
Waits for any input buttons.
uint32_t BUTTON_GetButtonsEvents (uint32_t *current)
Gets bitmap of button events.
uint32_t BUTTON_GetButtonsPushEvents (uint32_t *current)
Gets bitmap of button push events.
uint32_t BUTTON_GetButtonsReleaseEvents (uint32_t *current)
Gets bitmap of button release events.
void BUTTON_WaitRelease (void(*f)(void))
Waits until all buttons are released.
Detailed Description
Macro Definition Documentation
BUTTONS_MASK
#define BUTTONS_MASK (B1 | B2 | B3)
Mask for all 3 buttons.
Definition at line 47 of file button.h.
DEBOUNCE_TIME
#define DEBOUNCE_TIME 50
Debounce time.
Definition at line 42 of file button.h.
Enumeration Type Documentation
BUTTON
enum BUTTON
Input buttons.
Enumerator
B1
PO[1] -> Pin 43.
B2
PO[2] -> Pin 44.
B3
PO[3] -> Pin 45.
Definition at line 52 of file button.h.
Function Documentation
BUTTON_GetButtonsEvents()
uint32_t BUTTON_GetButtonsEvents (uint32_t * current)
Gets bitmap of button events.
Note
This is a non-blocking function.
Parameters
current -> Pointer to int, where current buttons state will be stored.
Note
If current buttons state is not wanted, current should be NULL (0).
Returns
If a certain button is in a different state comparing to the previous call to this function, the corresponding bit is returned as 1.
Definition at line 38 of file button.c.
Referenced by BUTTON_WaitRelease().
BUTTON_GetButtonsPushEvents()
uint32_t BUTTON_GetButtonsPushEvents (uint32_t * current)
Gets bitmap of button push events.
Note
This is a non-blocking function.
Parameters
current -> Pointer to int, where current buttons state will be stored.
Note
If current buttons state is not wanted, current should be NULL (0).
Returns
If a certain button is in a different state comparing to the previous call to this function and is pressed now, the corresponding bit is returned as 1.
Definition at line 52 of file button.c.
BUTTON_GetButtonsReleaseEvents()
uint32_t BUTTON_GetButtonsReleaseEvents (uint32_t * current)
Gets bitmap of button release events.
Note
This is a non-blocking function.
Parameters
current -> Pointer to int, where current buttons state will be stored.
Note
If current buttons state is not wanted, current should be NULL (0).
Returns
If a certain button is in a different state comparing to the previous call to this function and is not pressed now, the corresponding bit is returned as 1.
Definition at line 66 of file button.c.
BUTTON_Hit()
int32_t BUTTON_Hit (void)
Gets input buttons bitmap.
Note
This is a non-blocking function.
Returns
Returns input bitmap, i.e., 0 if no active input.
Definition at line 26 of file button.c.
References BUTTONS_MASK.
Referenced by BUTTON_Read(), and BUTTON_WaitRelease().
BUTTON_Init()
void BUTTON_Init (void)
Initialises the button API.
Note
This function must be called prior to any other BUTTON functions.
Definition at line 20 of file button.c.
References BUTTONS_MASK, SYS, and WAIT_Init().
BUTTON_Read()
int32_t BUTTON_Read (void)
Waits for any input buttons.
Note
This is a blocking function.
Returns
Returns input bitmap, i.e., 0 if no active input.
Definition at line 30 of file button.c.
References BUTTON_Hit().
BUTTON_WaitRelease()
void BUTTON_WaitRelease (void(*)(void) f)
Waits until all buttons are released.
Parameters
f -> Pointer to function to repeatedly execute while waiting. Write '0' if no function is needed. Should be 0 if no interest in such.
Note
This is a blocking function.
Definition at line 80 of file button.c.
References BUTTON_GetButtonsEvents(), and BUTTON_Hit().