Car Runner: CAR_RUNNER Public Functions
CAR_RUNNER Public Functions
CAR_RUNNER
Data Structures
struct CAR
Structure that will hold the Car's current location on the LCD.
Macros
#define CONFIG_OPTIONS 3
Number of entries in Configuration Mode menu.
#define TIME_CONFIG_FIELDS 6
Number of time fields to configure in Time Configuration Mode.
#define BUTTONS_HOLD_TIME 2000000
Necessary time to hold buttons, in order to enter/exit Configuration Mode.
#define SCORE_SHOW_TIME 3000000
Time between different scores being displayed, in Idle Mode.
#define HIGHLIGHT_BLINK_TIME 300000
Blinking time, used to highlight fields.
#define GAME_RATE 300000
Game update rate (i.e. time in us between each "frame"), in Game Mode.
#define FUEL_RATE 2000000
Fuel tank decrement rate, in Game Mode.
#define CAR_POSITION 3
Column in which user will visualise the car (should be < 10).
#define INITIAL_OBSTACLE_GAP CAR_POSITION + 5
Columns with no obstacles as of starting the game.
#define MAX_FUEL 8
Maximum fuel.
#define INCLINATION_THRESHOLD 60
Value ADXL345's Y-Axis needs to surpass, to count as row change.
#define CAR_BACK_CHAR 0
LCD special char for Car Back.
#define CAR_FRONT_CHAR 1
LCD special char for Car Front.
#define FUEL_CHAR 3
LCD special char for Fuel Galleon.
#define FUEL1_CHAR 4
LCD special char for Fuel indicator at 1/4.
#define FUEL2_CHAR 5
LCD special char for Fuel indicator at 2/4.
#define FUEL3_CHAR 6
LCD special char for Fuel indicator at 3/4.
#define FUEL4_CHAR 7
LCD special char for Fuel indicator at 4/4.
#define BARRIER_CHAR 2
LCD special char for Barrier.
Enumerations
enum STATE {
IDLE = 0, CONFIG = 1, CONFIG_DATE = 2, CONFIG_NAME = 3,
CONFIG_ERASE_SCORES = 4, SCORES_ERASED = 5, PREGAME = 6, GAME = 7,
POSTGAME = 8
}
States of the state machine:
Functions
void stateMachine (void)
State manager.
void getUsername (void)
Prompts an input interface to the LCD, so the user can enter his name.
void updateAndPrintTime (RTC_TIME_FIELD without)
Will print RTC time to the LCD.
void printScore (Score *score, int n)
Will print specified Score to the LCD.
void idle (void)
Idle Mode. The fundamental state of the program. Shows RTC time and best scores, alternately.
void changeRow (CAR *car, int row)
Changes LCD row specified 'Car' is on.
int getInclination (void)
Get ADXL345 Y-Axis and check for threshold (defined in macro) exceeds.
void printToCol (int col, unsigned char c1, unsigned char c2)
Print to an LCD column.
void shiftFuelIndicator (int *currentFuelCol)
Shift fuel indicator in LCD.
void shiftCar (CAR *car)
Shifts the whole car (i.e. front and back) 1 LCD column to the right.
void randomiseFuel (int from, int to, int map[LCD_DISPLAY_ROWS][LCD_DDRAM_LENGTH])
Randomises a unique fuel galleon in a specified range of the LCD DDRAM. Also updates array 'o' with such information.
void randomiseObstacles (int from, int to, int map[LCD_DISPLAY_ROWS][LCD_DDRAM_LENGTH])
Randomises new obstacles in a specified range of the LCD DDRAM. Also updates array 'o' with such information.
void checkForFuelGrab (CAR *car, int map[LCD_DISPLAY_ROWS][LCD_DDRAM_LENGTH])
Checks if any part of the Car (i.e. front or body) has hit a fuel galleon.
bool checkForLoss (CAR *car, int map[LCD_DISPLAY_ROWS][LCD_DDRAM_LENGTH])
Checks if any part of the Car (i.e. front or body) has hit a obstacle.
void pregame (void)
State to wait for user to ready up.
void game (void)
State that runs the actual game.
void postgame (void)
State to show user's score.
void config (void)
State in which the user can configure some features.
void timeConfig (void)
State in which the user may configure RTC time.
void scoresErased (void)
State that tells the user the scores were erased.
bool yesOrNo (void(*f)(void))
Prompts the user with a 'Yes or No' interface, and runs the specified function if 'Yes' option is selected.
Variables
unsigned char car_back_charmap []
Char map for Car Back.
unsigned char fuel_charmap []
Char map for Fuel Galleon.
unsigned char car_front_charmap []
Char map for Car Front.
unsigned char barrier_charmap []
Char map for Barrier.
unsigned char fuel4_charmap []
Char map for 4/4 fuel indicator.
unsigned char fuel3_charmap []
Char map for 3/4 fuel indicator.
unsigned char fuel2_charmap []
Char map for 2/4 fuel indicator.
unsigned char fuel1_charmap []
Char map for 1/4 fuel indicator.
volatile STATE state = IDLE
Current state (starts as IDLE).
char username [NAME_LENGTH+1]
Name of current user.
Detailed Description
Macro Definition Documentation
BARRIER_CHAR
#define BARRIER_CHAR 2
LCD special char for Barrier.
Note
Shouldn't be changed.
Definition at line 152 of file car_runner.h.
CAR_BACK_CHAR
#define CAR_BACK_CHAR 0
LCD special char for Car Back.
Note
Shouldn't be changed.
Definition at line 110 of file car_runner.h.
CAR_FRONT_CHAR
#define CAR_FRONT_CHAR 1
LCD special char for Car Front.
Note
Shouldn't be changed.
Definition at line 116 of file car_runner.h.
CONFIG_OPTIONS
#define CONFIG_OPTIONS 3
Number of entries in Configuration Mode menu.
Note
Shouldn't be changed.
Definition at line 52 of file car_runner.h.
FUEL1_CHAR
#define FUEL1_CHAR 4
LCD special char for Fuel indicator at 1/4.
Note
Shouldn't be changed.
Definition at line 128 of file car_runner.h.
FUEL2_CHAR
#define FUEL2_CHAR 5
LCD special char for Fuel indicator at 2/4.
Note
Shouldn't be changed.
Definition at line 134 of file car_runner.h.
FUEL3_CHAR
#define FUEL3_CHAR 6
LCD special char for Fuel indicator at 3/4.
Note
Shouldn't be changed.
Definition at line 140 of file car_runner.h.
FUEL4_CHAR
#define FUEL4_CHAR 7
LCD special char for Fuel indicator at 4/4.
Note
Shouldn't be changed.
Definition at line 146 of file car_runner.h.
FUEL_CHAR
#define FUEL_CHAR 3
LCD special char for Fuel Galleon.
Note
Shouldn't be changed.
Definition at line 122 of file car_runner.h.
MAX_FUEL
#define MAX_FUEL 8
Maximum fuel.
Note
Shouldn't be changed.
Definition at line 99 of file car_runner.h.
TIME_CONFIG_FIELDS
#define TIME_CONFIG_FIELDS 6
Number of time fields to configure in Time Configuration Mode.
Note
Shouldn't be changed.
Definition at line 58 of file car_runner.h.
Enumeration Type Documentation
STATE
enum STATE
States of the state machine:
Enumerator
IDLE
Main menu.
CONFIG
Configuration menu.
CONFIG_DATE
Date configuration.
CONFIG_NAME
Name configuration.
CONFIG_ERASE_SCORES
Clear scores.
SCORES_ERASED
Screen indicating scores were erased.
PREGAME
Screen that waits for user to ready up.
GAME
Actual game.
POSTGAME
Screen that shows user's score.
Definition at line 167 of file car_runner.h.
Function Documentation
changeRow()
void changeRow (CAR * car, int row)
Changes LCD row specified 'Car' is on.
Parameters
car -> Pointer to Structure Car.
row -> New row.
Note
If row is different from 1 or 2, this function does nothing.
Definition at line 402 of file car_runner.c.
References CAR::row.
Referenced by game().
checkForFuelGrab()
void checkForFuelGrab (CAR * car, int map[LCD_DISPLAY_ROWS][LCD_DDRAM_LENGTH])
Checks if any part of the Car (i.e. front or body) has hit a fuel galleon.
Parameters
car -> Pointer to Car.
map -> Array representing all objects currently in LCD DDRAM (2 for fuel galleon, 1 for obstacle, 0 for nothing).
Note
If a galleon has been hit, fuel is added to the fuel indicator.
Definition at line 541 of file car_runner.c.
References CAR::back_column, CAR::front_column, MAX_FUEL, and CAR::row.
Referenced by game().
checkForLoss()
bool checkForLoss (CAR * car, int map[LCD_DISPLAY_ROWS][LCD_DDRAM_LENGTH])
Checks if any part of the Car (i.e. front or body) has hit a obstacle.
Parameters
car -> Pointer to Car.
map -> Array representing all objects currently in LCD DDRAM (2 for fuel galleon, 1 for obstacle, 0 for nothing).
Returns
If an obstacle has been hit, returns true. Else, returns false.
Definition at line 554 of file car_runner.c.
References CAR::back_column, CAR::front_column, and CAR::row.
Referenced by game().
config()
void config (void)
State in which the user can configure some features.
Note
Use B1 and B2 to scroll through the different options.
Use B3 to select highlighted option.
This function uses Timer0.
When selecting an option or going back to Idle Mode, it's guaranteed that Timer0 is no longer busy.
Definition at line 650 of file car_runner.c.
References BUTTONS_HOLD_TIME, CONFIG_DATE, CONFIG_ERASE_SCORES, CONFIG_NAME, CONFIG_OPTIONS, IDLE, state, and username.
Referenced by stateMachine().
game()
void game (void)
State that runs the actual game.
Note
Tilt the ADXL345 component to change the row the Car is on.
This function uses Timer0 and Timer1.
Definition at line 567 of file car_runner.c.
References CAR::back_column, CAR_POSITION, changeRow(), checkForFuelGrab(), checkForLoss(), FUEL_RATE, GAME_RATE, getInclination(), INITIAL_OBSTACLE_GAP, MAX_FUEL, randomiseFuel(), randomiseObstacles(), CAR::row, shiftCar(), and shiftFuelIndicator().
Referenced by stateMachine().
getInclination()
int getInclination (void)
Get ADXL345 Y-Axis and check for threshold (defined in macro) exceeds.
Returns
0 if no threshold has been exceeded. -1 for left threshold, 1 for right threshold.
Definition at line 407 of file car_runner.c.
References INCLINATION_THRESHOLD.
Referenced by game().
getUsername()
void getUsername (void)
Prompts an input interface to the LCD, so the user can enter his name.
Note
Use B1 and B2 to increment and decrement, respectively, each character field, using B3 to advance.
This function doesn't clear the LCD display, upon exit.
This function uses Timer0. However, it's guaranteed that Timer0 is no longer busy upon this function's return.
Definition at line 106 of file car_runner.c.
References HIGHLIGHT_BLINK_TIME, NAME_LENGTH, and username.
Referenced by stateMachine().
idle()
void idle (void)
Idle Mode. The fundamental state of the program. Shows RTC time and best scores, alternately.
Note
Use B1 and B2 to scroll between 'Time' and 'Best Scores'.
Use B3 to enter Game Mode.
Hold B1 and B2 for a certain amount of time to enter Configuration Mode.
This function never clears the LCD display, upon exit.
This function uses Timer0 and Timer1.
When entering Game Mode, it's guaranteed both timers are no longer busy.
When entering Configuration Mode, it's guaranteed that Timer0 is no longer busy, but not Timer1 (since it won't be used).
Definition at line 302 of file car_runner.c.
References BUTTONS_HOLD_TIME, CONFIG, getScore(), PREGAME, printScore(), SCORE_SHOW_TIME, state, and updateAndPrintTime().
Referenced by stateMachine().
postgame()
void postgame (void)
State to show user's score.
Note
Hit any button to go to menu.
This function waits for timer0 and timer1, both used in 'game()'.
Definition at line 620 of file car_runner.c.
References NAME_LENGTH, saveScore(), and username.
Referenced by stateMachine().
pregame()
void pregame (void)
State to wait for user to ready up.
Note
Hit any button to start the game.
Definition at line 558 of file car_runner.c.
Referenced by stateMachine().
printScore()
void printScore (Score * score, int n)
Will print specified Score to the LCD.
Parameters
score -> Pointer to specified Score.
n -> Placement of score (p.e. if 'score' is the second best, write 1).
Note
This function doesn't clear the LCD display, upon exit.
Definition at line 244 of file car_runner.c.
References Score::name, and Score::score.
Referenced by idle().
printToCol()
void printToCol (int col, unsigned char c1, unsigned char c2)
Print to an LCD column.
Parameters
col -> Column where chars should be printed.
c1 -> Char to print in row 1.
c2 -> Char to print in row 2.
Definition at line 416 of file car_runner.c.
Referenced by shiftFuelIndicator().
randomiseFuel()
void randomiseFuel (int from, int to, int map[LCD_DISPLAY_ROWS][LCD_DDRAM_LENGTH])
Randomises a unique fuel galleon in a specified range of the LCD DDRAM. Also updates array 'o' with such information.
Parameters
from -> Randomisation will start in this column.
to -> Randomisation will end in this column.
map -> Array representing all objects currently in LCD DDRAM (2 for fuel galleon, 1 for obstacle, 0 for nothing).
Note
Only places the fuel in a column where there's no obstacles in either row.
Definition at line 486 of file car_runner.c.
References FUEL_CHAR.
Referenced by game().
randomiseObstacles()
void randomiseObstacles (int from, int to, int map[LCD_DISPLAY_ROWS][LCD_DDRAM_LENGTH])
Randomises new obstacles in a specified range of the LCD DDRAM. Also updates array 'o' with such information.
Parameters
from -> Randomisation will start in this column.
to -> Randomisation will end in this column.
map -> Array representing all objects currently in LCD DDRAM (2 for fuel galleon, 1 for obstacle, 0 for nothing).
Note
A space of at least 2 columns is always left between each obstacle.
Definition at line 506 of file car_runner.c.
References BARRIER_CHAR.
Referenced by game().
scoresErased()
void scoresErased (void)
State that tells the user the scores were erased.
Note
Hit any button to go back.
Definition at line 801 of file car_runner.c.
Referenced by stateMachine().
shiftCar()
void shiftCar (CAR * car)
Shifts the whole car (i.e. front and back) 1 LCD column to the right.
Parameters
car -> Pointer to Car.
Note
The LCD display is never shifted in this function. Only the car is shifted.
Definition at line 465 of file car_runner.c.
References CAR::back_column, CAR_BACK_CHAR, CAR_FRONT_CHAR, CAR::front_column, CAR::last_row, and CAR::row.
Referenced by game().
shiftFuelIndicator()
void shiftFuelIndicator (int * currentFuelCol)
Shift fuel indicator in LCD.
Parameters
currentFuelCol -> Column where fuel indicator is, currently.
Note
Fuel indicator will be shifted to the right of 'currentFuelCol'.
This function calls 'printToCol()' to print the fuel indicator to the next column.
The LCD display is never shifted in this function. Only the fuel indicator is shifted.
Definition at line 423 of file car_runner.c.
References FUEL1_CHAR, FUEL2_CHAR, FUEL3_CHAR, FUEL4_CHAR, and printToCol().
Referenced by game().
stateMachine()
void stateMachine (void)
State manager.
Functions:
Note
Will decide which state to call, based in 'STATE' ENUM value stored in 'state'.
Will clear the LCD display in every state transition.
Definition at line 34 of file car_runner.c.
References CONFIG, config(), CONFIG_DATE, CONFIG_ERASE_SCORES, CONFIG_NAME, eraseScores(), GAME, game(), getUsername(), IDLE, idle(), POSTGAME, postgame(), PREGAME, pregame(), SCORES_ERASED, scoresErased(), state, timeConfig(), and yesOrNo().
timeConfig()
void timeConfig (void)
State in which the user may configure RTC time.
Note
Use B1 and B2 to increment and decrement, respectively, the highlighted time field.
Use B3 advance to next time field.
This function uses Timer0.
When leaving this function, it's guaranteed that Timer0 is no longer busy.
Definition at line 757 of file car_runner.c.
References HIGHLIGHT_BLINK_TIME, TIME_CONFIG_FIELDS, and updateAndPrintTime().
Referenced by stateMachine().
updateAndPrintTime()
void updateAndPrintTime (RTC_TIME_FIELD without)
Will print RTC time to the LCD.
Parameters
without -> Specified field not to be printed (this can be used for highlight blinking purposes).
Note
This function doesn't clear the LCD display, upon exit.
Definition at line 176 of file car_runner.c.
Referenced by idle(), and timeConfig().
yesOrNo()
bool yesOrNo (void(*)(void) f)
Prompts the user with a 'Yes or No' interface, and runs the specified function if 'Yes' option is selected.
Parameters
f -> Pointer to function that shall be ran upon selection of 'Yes' option.
Returns
returns true if 'yes' was chosen, or false if 'no' was chosen.
Note
Use B1 and B2 to scroll through 'Yes' and 'No' options.
Use B3 to select highlighted option.
Definition at line 811 of file car_runner.c.
Referenced by stateMachine().
Variable Documentation
barrier_charmap
unsigned char barrier_charmap[]
Initial value:
= {
    0x02,
    0x0E,
    0x02,
    0x02,
    0x02,
    0x0E,
    0x02,
    0x00
}
Char map for Barrier.
Definition at line 225 of file car_runner.h.
car_back_charmap
unsigned char car_back_charmap[]
Initial value:
= {
    0x00,
    0x06,
    0x07,
    0x06,
    0x07,
    0x06,
    0x00,
    0x00
}
Char map for Car Back.
Definition at line 183 of file car_runner.h.
car_front_charmap
unsigned char car_front_charmap[]
Initial value:
= {
    0x00,
    0x0C,
    0x1E,
    0x02,
    0x1E,
    0x0C,
    0x00,
    0x00
}
Char map for Car Front.
Definition at line 211 of file car_runner.h.
fuel1_charmap
unsigned char fuel1_charmap[]
Initial value:
= {
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x1f,
    0x1f
}
Char map for 1/4 fuel indicator.
Definition at line 281 of file car_runner.h.
fuel2_charmap
unsigned char fuel2_charmap[]
Initial value:
= {
    0x00,
    0x00,
    0x00,
    0x00,
    0x1f,
    0x1f,
    0x1f,
    0x1f
}
Char map for 2/4 fuel indicator.
Definition at line 267 of file car_runner.h.
fuel3_charmap
unsigned char fuel3_charmap[]
Initial value:
= {
    0x00,
    0x00,
    0x1f,
    0x1f,
    0x1f,
    0x1f,
    0x1f,
    0x1f
}
Char map for 3/4 fuel indicator.
Definition at line 253 of file car_runner.h.
fuel4_charmap
unsigned char fuel4_charmap[]
Initial value:
= {
    0x1f,
    0x1f,
    0x1f,
    0x1f,
    0x1f,
    0x1f,
    0x1f,
    0x1f
}
Char map for 4/4 fuel indicator.
Definition at line 239 of file car_runner.h.
fuel_charmap
unsigned char fuel_charmap[]
Initial value:
= {
    0x00,
    0x1C,
    0x07,
    0x0F,
    0x0F,
    0x0F,
    0x00,
    0x00
}
Char map for Fuel Galleon.
Definition at line 197 of file car_runner.h.
state
volatile STATE state = IDLE
Current state (starts as IDLE).
Variables:
Definition at line 304 of file car_runner.h.
Referenced by config(), idle(), and stateMachine().