Embedded Systems Library: LED Public Functions
LED Public Functions
LED
Macros
#define LED2 (1 << 22)
Internal LED -> PO[22].
Functions
void LED_Init (bool state)
Initialises the LED API.
bool LED_GetState (void)
Checks LED state.
void LED_On (void)
Turns LED on.
void LED_Off (void)
Turns LED off.
void LED_Invert (void)
Invert LED state.
Detailed Description
Macro Definition Documentation
LED2
#define LED2 (1 << 22)
Internal LED -> PO[22].
Definition at line 40 of file led.h.
Function Documentation
LED_GetState()
bool LED_GetState (void)
Checks LED state.
Returns
Returns true if LED is on, false if LED is off.
Definition at line 25 of file led.c.
References LED2.
Referenced by LED_Invert().
LED_Init()
void LED_Init (bool state)
Initialises the LED API.
Parameters
state -> If true, leaves LED on. If false, leaves LED off.
Note
This function must be called prior to any other LED functions.
Definition at line 16 of file led.c.
References LED2.
LED_Invert()
void LED_Invert (void)
Invert LED state.
Definition at line 40 of file led.c.
References LED_GetState(), LED_Off(), and LED_On().
LED_Off()
void LED_Off (void)
Turns LED off.
Definition at line 35 of file led.c.
References LED2.
Referenced by LED_Invert().
LED_On()
void LED_On (void)
Turns LED on.
Definition at line 30 of file led.c.
References LED2.
Referenced by LED_Invert().