Embedded Systems Library: ESP Public Functions
ESP Public Functions
ESP
Data Structures
struct ESP_AP
Structure representing Access Point.
Macros
#define ESP_TIMEOUT_MS 2000
Default timeout time.
#define ESP_LONG_TIMEOUT_MS 20000
Long timeout time.
#define AT_MAX_IPD_PACKET 2048
Max length of packet received.
#define AT_CMD_SUFFIX "\r\n"
Suffix to all AT Commands.
#define AT_RESPONSE_MAX_LENGTH 1024
Max length considered for an AT Command Response.
#define ESP_RST (1 << 27)
ESP_01 Reset pins.
#define MAX_CWLAP_SIZE 512
Max size of a CWLAP AP response.
#define MAX_AP_NUM 10
Maximum number of AP's to request.
#define MAX_SSID_LENGTH 128
Maximum length of AP's SSID.
Enumerations
enum ESP_PROTOCOL { ESP_TCP, ESP_UDP }
Network protocol useb by ESP.
enum ESP_MODE { ESP_STATION, ESP_SOFTAP, ESP_BOTH }
ESP transmission mode.
enum ESP_CONNECTION { ESP_SINGLE, ESP_MULTIPLE }
ESP connection type.
Functions
bool ESP_Init (unsigned int baud)
Test if ESP-8266 module is properly started.
uint32_t ESP_Test (void)
Test if ESP-8266 module is properly started.
uint32_t ESP_Restart (void)
Restart ESP-8266 module.
uint32_t ESP_Version (void)
Read version information.
uint32_t ESP_EnableEcho (bool echo)
Enable/disable command echoing.
uint32_t ESP_Mode (ESP_MODE mode, bool save_to_flash)
Set WiFi mode.
uint32_t ESP_ConfigureConnection (ESP_CONNECTION con)
Set Connection type.
uint32_t ESP_ListAP (char list[MAX_AP_NUM][MAX_SSID_LENGTH], bool sort)
Get list of nearby Access Points.
uint32_t ESP_Connect (char *ssid, char *pass, bool save_to_flash)
Connect to an access point.
uint32_t ESP_Disconnect (void)
Disconnect from access point.
uint32_t ESP_Ip (unsigned char *ip)
Get the current local IPv4 address.
uint32_t ESP_Start (ESP_PROTOCOL protocol, char *ip, char *port, char *keepalive)
Open a TCP or UDP connection.
uint32_t ESP_Close (void)
Close current connection.
uint32_t ESP_Status (void)
Get status of connection.
uint32_t ESP_SendData (char *data, int len)
Send data over connection.
uint32_t ESP_ReceiveData (char *data, uint32_t max_len)
Receive data over connection. Waits for +IPD and reads data until max_len is met or data ends. If last call to this function left data in the buffer, this function will first look at that data, and only then wait for a new +IPD, if max_len hasn't been met.
uint32_t ESP_WriteString (char *cmd)
Send AT string.
uint32_t ESP_ReadString (char *response, uint32_t timeout)
Receive AT string response.
uint32_t ESP_WriteBuffer (char *cmd, uint32_t len)
Send AT buffer.
uint32_t ESP_ReadBuffer (char *response, uint32_t len, uint32_t timeout)
Receive AT buffer response.
void ESP_WriteChar (char ch)
Send a character to ESP.
bool ESP_ReadChar (char *ch, uint32_t timeout)
Receive a character from ESP.
bool ESP_GetChar (char *ch)
Receive a character from ESP, if there is one.
uint32_t ESP_WaitForString (uint32_t timeout, int resNum,...)
Wait for ESP to meet one of a certain amount of string responses.
uint32_t ESP_WaitFor (char *response, uint32_t timeout)
Wait for ESP to meet a certain response (not necessarily a string with '\0').
Detailed Description
Macro Definition Documentation
AT_CMD_SUFFIX
#define AT_CMD_SUFFIX "\r\n"
Suffix to all AT Commands.
Definition at line 64 of file esp.h.
AT_MAX_IPD_PACKET
#define AT_MAX_IPD_PACKET 2048
Max length of packet received.
Definition at line 59 of file esp.h.
AT_RESPONSE_MAX_LENGTH
#define AT_RESPONSE_MAX_LENGTH 1024
Max length considered for an AT Command Response.
Definition at line 69 of file esp.h.
ESP_LONG_TIMEOUT_MS
#define ESP_LONG_TIMEOUT_MS 20000
Long timeout time.
Definition at line 54 of file esp.h.
ESP_RST
#define ESP_RST (1 << 27)
ESP_01 Reset pins.
Definition at line 74 of file esp.h.
ESP_TIMEOUT_MS
#define ESP_TIMEOUT_MS 2000
Default timeout time.
Definition at line 49 of file esp.h.
MAX_AP_NUM
#define MAX_AP_NUM 10
Maximum number of AP's to request.
Definition at line 84 of file esp.h.
MAX_CWLAP_SIZE
#define MAX_CWLAP_SIZE 512
Max size of a CWLAP AP response.
Definition at line 79 of file esp.h.
MAX_SSID_LENGTH
#define MAX_SSID_LENGTH 128
Maximum length of AP's SSID.
Definition at line 89 of file esp.h.
Enumeration Type Documentation
ESP_CONNECTION
enum ESP_CONNECTION
ESP connection type.
Enumerator
ESP_SINGLE
Single Connection.
ESP_MULTIPLE
Multiple Connection.
Definition at line 112 of file esp.h.
ESP_MODE
enum ESP_MODE
ESP transmission mode.
Enumerator
ESP_STATION
Station Mode.
ESP_SOFTAP
Access Point Mode.
ESP_BOTH
Both Station and Access Point Mode.
Definition at line 103 of file esp.h.
ESP_PROTOCOL
enum ESP_PROTOCOL
Network protocol useb by ESP.
Enumerator
ESP_TCP
TCP Protocol.
ESP_UDP
UDP Protocol.
Definition at line 95 of file esp.h.
Function Documentation
ESP_Close()
uint32_t ESP_Close (void)
Close current connection.
Returns
0: Successfully closed connection. -1: Error.
Definition at line 224 of file esp.c.
References AT_CMD_SUFFIX, ESP_LONG_TIMEOUT_MS, ESP_WaitForString(), and ESP_WriteString().
Referenced by NETWORK_GetSeconds().
ESP_ConfigureConnection()
uint32_t ESP_ConfigureConnection (ESP_CONNECTION con)
Set Connection type.
Parameters
con -> Can be ESP_SINGLE or ESO_MULTIPLE.
Returns
0 if connection type was correctly set; 1 if a connection is already established; 2 if an error was received from ESP-8266; -1 if an UART error occurred.
Definition at line 109 of file esp.c.
References AT_CMD_SUFFIX, ESP_MULTIPLE, ESP_SINGLE, ESP_TIMEOUT_MS, ESP_WaitForString(), and ESP_WriteString().
Referenced by NETWORK_ConnectToAP().
ESP_Connect()
uint32_t ESP_Connect (char * ssid, char * pass, bool save_to_flash)
Connect to an access point.
Parameters
ssid -> The SSID to connect to.
pass -> The password of the network.
save_to_flash -> Whether to save configuration to flash or not.
Returns
0 if connection started successfully; 1 if an error was received from ESP-8266; -1 if an UART error occurred.
Definition at line 152 of file esp.c.
References AT_CMD_SUFFIX, ESP_LONG_TIMEOUT_MS, ESP_WaitForString(), and ESP_WriteString().
Referenced by NETWORK_ConnectToAP().
ESP_Disconnect()
uint32_t ESP_Disconnect (void)
Disconnect from access point.
Returns
0 if successfully disconnected, -1 otherwise.
Definition at line 165 of file esp.c.
References AT_CMD_SUFFIX, ESP_LONG_TIMEOUT_MS, ESP_WaitForString(), and ESP_WriteString().
ESP_EnableEcho()
uint32_t ESP_EnableEcho (bool echo)
Enable/disable command echoing.
Parameters
echo -> If true, echo is enabled.
Returns
0 if successful, -1 otherwise.
Definition at line 84 of file esp.c.
References AT_CMD_SUFFIX, ESP_TIMEOUT_MS, ESP_WaitForString(), and ESP_WriteString().
Referenced by NETWORK_ConnectToAP().
ESP_GetChar()
bool ESP_GetChar (char * ch)
Receive a character from ESP, if there is one.
Parameters
ch -> Pointer to character read.
Returns
True if a character was read. False if no character was found.
Definition at line 338 of file esp.c.
References UART_GetChar().
Referenced by ESP_Init().
ESP_Init()
bool ESP_Init (unsigned int baud)
Test if ESP-8266 module is properly started.
Parameters
baud -> Baud Rate.
Returns
true if it is started, false otherwise.
Definition at line 37 of file esp.c.
References ESP_GetChar(), ESP_RST, SYS, UART_Init(), WAIT_Init(), and WAIT_SYS_Ms().
Referenced by NETWORK_ConnectToAP().
ESP_Ip()
uint32_t ESP_Ip (unsigned char * ip)
Get the current local IPv4 address.
Parameters
ip -> String in which IP will be written.
Returns
0 if IP was successfully read, -1 otherwise.
Note
The result will not be stored as a string but byte by byte. For example, for the IP 192.168.0.1, the value of store_in will be: {0xc0, 0xa8, 0x00, 0x01}.
Definition at line 171 of file esp.c.
References AT_CMD_SUFFIX, ESP_ReadChar(), ESP_TIMEOUT_MS, ESP_WaitForString(), and ESP_WriteString().
ESP_ListAP()
uint32_t ESP_ListAP (char list[MAX_AP_NUM][MAX_SSID_LENGTH], bool sort)
Get list of nearby Access Points.
Parameters
list -> Array of AP's where list should be written.
sort -> If true, results will be sorted according to the RSSI parameter (signal strength).
Returns
Number of AP's written to list.
Definition at line 123 of file esp.c.
ESP_Mode()
uint32_t ESP_Mode (ESP_MODE mode, bool save_to_flash)
Set WiFi mode.
Parameters
mode -> Can be ESP_STATION or ESO_SOFTAP.
save_to_flash -> Whether to save configuration to flash or not.
Returns
0 if mode was correctly set, -1 otherwise.
Definition at line 91 of file esp.c.
References AT_CMD_SUFFIX, ESP_BOTH, ESP_SOFTAP, ESP_STATION, ESP_TIMEOUT_MS, ESP_WaitForString(), and ESP_WriteString().
Referenced by NETWORK_ConnectToAP().
ESP_ReadBuffer()
uint32_t ESP_ReadBuffer (char * response, uint32_t len, uint32_t timeout)
Receive AT buffer response.
Parameters
response -> Buffer.
len -> Buffer length in bytes.
timeout -> UART timeout in ms.
Returns
Number of bytes got.
Definition at line 346 of file esp.c.
ESP_ReadChar()
bool ESP_ReadChar (char * ch, uint32_t timeout)
Receive a character from ESP.
Parameters
ch -> Where character will be written to.
timeout -> UART timeout in ms.
Returns
True if a character was read, false if timeout was met.
Note
If no character is found, function will block, waiting for one.
Definition at line 334 of file esp.c.
References UART_ReadChar().
Referenced by ESP_Ip(), and ESP_WaitFor().
ESP_ReadString()
uint32_t ESP_ReadString (char * response, uint32_t timeout)
Receive AT string response.
Parameters
response -> Response received.
timeout -> UART timeout in ms.
Returns
Number of bytes got.
Definition at line 342 of file esp.c.
References UART_ReadString().
Referenced by ESP_Status(), and ESP_WaitForString().
ESP_ReceiveData()
uint32_t ESP_ReceiveData (char * data, uint32_t max_len)
Receive data over connection. Waits for +IPD and reads data until max_len is met or data ends. If last call to this function left data in the buffer, this function will first look at that data, and only then wait for a new +IPD, if max_len hasn't been met.
Parameters
data -> Where data will be written to.
max_len -> Maximum length expected. If this length is met before length of +IPD, only max_len is returned. Although, UART still reads the rest, so it's not left abandoned.
Returns
Bytes read.
Definition at line 252 of file esp.c.
Referenced by NETWORK_GetSeconds().
ESP_Restart()
uint32_t ESP_Restart (void)
Restart ESP-8266 module.
Returns
0 if it was properly restarted, -1 otherwise.
Definition at line 71 of file esp.c.
References AT_CMD_SUFFIX, ESP_TIMEOUT_MS, ESP_WaitForString(), and ESP_WriteString().
ESP_SendData()
uint32_t ESP_SendData (char * data, int len)
Send data over connection.
Parameters
data -> Data to send.
len -> Length of data.
Returns
0 if data was sent correctly; 1 if ESP-8266 failed to send the data; 2 if an error was received from ESP-8266; -1 if an UART error occurred.
Definition at line 241 of file esp.c.
Referenced by NETWORK_GetSeconds().
ESP_Start()
uint32_t ESP_Start (ESP_PROTOCOL protocol, char * ip, char * port, char * keepalive)
Open a TCP or UDP connection.
Parameters
protocol -> Either ESP_TCP or ESP_UDP.
ip -> String containing the IP or host name to connect to.
port -> The port to connect to.
keepalive -> Detection time interval in which TCP connection is kept alive. Only relevant when protocol = ESP_TCP. Max of 7200.
Returns
0 if connection successfully started; 1 if a connection was already started, but driver didn't keep track of it; 2 if an error was received from ESP-8266; -1 if an UART error occurred; -2 if a connection was already started.
Definition at line 201 of file esp.c.
References AT_CMD_SUFFIX, ESP_LONG_TIMEOUT_MS, ESP_TCP, ESP_WaitForString(), and ESP_WriteString().
Referenced by NETWORK_GetSeconds().
ESP_Status()
uint32_t ESP_Status (void)
Get status of connection.
Returns
2: The ESP8266 Station is connected to an AP and its IP is obtained. 3: The ESP8266 Station has created a TCP or UDP transmission. 4: The TCP or UDP transmission of ESP8266 Station is disconnected. 5: The ESP8266 Station does NOT connect to an AP.
Definition at line 231 of file esp.c.
References AT_CMD_SUFFIX, ESP_ReadString(), ESP_TIMEOUT_MS, ESP_WaitFor(), ESP_WaitForString(), and ESP_WriteString().
ESP_Test()
uint32_t ESP_Test (void)
Test if ESP-8266 module is properly started.
Returns
0 if it is started, -1 otherwise.
Definition at line 65 of file esp.c.
References AT_CMD_SUFFIX, ESP_TIMEOUT_MS, ESP_WaitForString(), and ESP_WriteString().
ESP_Version()
uint32_t ESP_Version (void)
Read version information.
Returns
0 if successful, -1 otherwise.
Definition at line 78 of file esp.c.
References AT_CMD_SUFFIX, ESP_TIMEOUT_MS, ESP_WaitForString(), and ESP_WriteString().
ESP_WaitFor()
uint32_t ESP_WaitFor (char * response, uint32_t timeout)
Wait for ESP to meet a certain response (not necessarily a string with '\0').
Parameters
response -> String response.
timeout -> UART timeout in ms.
Returns
Number of bytes read.
Note
This function reads from UART char by char, until response is met.
Definition at line 306 of file esp.c.
References ESP_ReadChar().
Referenced by ESP_Status().
ESP_WaitForString()
uint32_t ESP_WaitForString (uint32_t timeout, int resNum, ...)
Wait for ESP to meet one of a certain amount of string responses.
Parameters
timeout -> UART timeout in ms.
resNum -> Number of responses to consider.
... -> String responses.
Returns
The index of response met.
Note
This function reads from UART string by string, until a response is met.
Definition at line 284 of file esp.c.
References ESP_ReadString().
Referenced by ESP_Close(), ESP_ConfigureConnection(), ESP_Connect(), ESP_Disconnect(), ESP_EnableEcho(), ESP_Ip(), ESP_Mode(), ESP_Restart(), ESP_Start(), ESP_Status(), ESP_Test(), and ESP_Version().
ESP_WriteBuffer()
uint32_t ESP_WriteBuffer (char * cmd, uint32_t len)
Send AT buffer.
Parameters
cmd -> Buffer.
len -> Buffer length in bytes.
Returns
Number of bytes put.
Definition at line 326 of file esp.c.
ESP_WriteChar()
void ESP_WriteChar (char ch)
Send a character to ESP.
Returns
Number of bytes got.
Parameters
ch -> Character to write.
Definition at line 330 of file esp.c.
References UART_WriteChar().
ESP_WriteString()
uint32_t ESP_WriteString (char * cmd)
Send AT string.
Parameters
cmd -> String.
Returns
Number of bytes put.
Definition at line 322 of file esp.c.
References UART_WriteString().
Referenced by ESP_Close(), ESP_ConfigureConnection(), ESP_Connect(), ESP_Disconnect(), ESP_EnableEcho(), ESP_Ip(), ESP_Mode(), ESP_Restart(), ESP_Start(), ESP_Status(), ESP_Test(), and ESP_Version().