Embedded Systems Library: SPI Public Functions
SPI Public Functions
I2C
Macros
#define I2C_TIMEOUT_MS 100
I2C's maximum time (milliseconds) the device driver will wait before timing out.
#define I2C_BUFFER_LENGTH 1024
I2C's maximum buffer length for writing and reading.
Enumerations
enum I2C_PCONP_ENABLE { I2C0_PCONP_ENABLE = (1 << 7), I2C1_PCONP_ENABLE = (1 << 19), I2C2_PCONP_ENABLE = (1 << 26) }
I2C's interface power/clock control bit.
enum I2C_PINS { SDA1 = 0, SCL1 = 1, SDA2 = 10, SCL2 = 11 }
I2C's PINs.
enum I2C_PINSEL { I2C1_PINSEL = 0x03, I2C2_PINSEL = 0x02 }
I2C's pin modes.
enum I2C_CONTROL {
AA = (1 << 2), SI = (1 << 3), STO = (1 << 4), STA = (1 << 5),
I2EN = (1 << 6)
}
I2C's control register bits.
enum I2C_STATE { I2C_IDLE = 0, I2C_BUSY = 1 }
I2C device driver states.
enum I2C_STATUS_MODE {
I2C_START = 0x08, I2C_REPEATED_START = 0x10, I2C_SLAW_ACK = 0x18, I2C_SLAW_NACK = 0x20,
I2C_DATAW_ACK = 0x28, I2C_DATAW_NACK = 0x30, I2C_ARBITRATION_LOST = 0x38, I2C_SLAR_ACK = 0x40,
I2C_SLAR_NACK = 0x48, I2C_DATAR_ACK = 0x50, I2C_DATAR_NACK = 0x58
}
Different modes found in Status Register when an interruption is fired.
Functions
void I2C1_Init ()
Initialises I2C1 interface.
void I2C2_Init ()
Initialises I2C2 interface.
int I2C1_Configure (int frequency, int rSize, char *wBuffer, int wSize)
Configures I2C1 interface.
int I2C2_Configure (int frequency, int rSize, char *wBuffer, int wSize)
Configures I2C2 interface.
int I2C1_Start ()
Start a transmission in I2C1 interface (read or write).
int I2C2_Start ()
Start a transmission in I2C2 interface (read or write).
void I2C1_Stop ()
Ends a started transmission on interface I2C1.
void I2C2_Stop ()
Ends a started transmission on interface I2C2.
int I2C1_Engine ()
Synchronously waits for the transmission on interface I2C1 to end.
int I2C2_Engine ()
Synchronously waits for the transmission on interface I2C2 to end.
void I2C1_GetBuffer (char *buffer)
Copy data in read buffer on IC1 interface to specified pointer.
void I2C2_GetBuffer (char *buffer)
Copy data in read buffer on IC2 interface to specified pointer.
Detailed Description
Macro Definition Documentation
I2C_BUFFER_LENGTH
#define I2C_BUFFER_LENGTH 1024
I2C's maximum buffer length for writing and reading.
Definition at line 47 of file i2c.h.
I2C_TIMEOUT_MS
#define I2C_TIMEOUT_MS 100
I2C's maximum time (milliseconds) the device driver will wait before timing out.
Definition at line 42 of file i2c.h.
Enumeration Type Documentation
I2C_CONTROL
enum I2C_CONTROL
I2C's control register bits.
Enumerator
AA
Assert Acknowledge bit.
SI
Interrupt bit.
STO
Stop bit.
STA
Start bit.
I2EN
Enable Interrupt bit.
Definition at line 79 of file i2c.h.
I2C_PCONP_ENABLE
enum I2C_PCONP_ENABLE
I2C's interface power/clock control bit.
Enumerator
I2C0_PCONP_ENABLE
Power/clock control bit for I2C0.
I2C1_PCONP_ENABLE
Power/clock control bit for I2C1.
I2C2_PCONP_ENABLE
Power/clock control bit for I2C2.
Definition at line 52 of file i2c.h.
I2C_PINS
enum I2C_PINS
I2C's PINs.
Enumerator
SDA1
P0[0] -> Pin 9.
SCL1
P0[1] -> Pin 10.
SDA2
P0[10] -> Pin 40.
SCL2
P0[11] -> Pin 41.
Definition at line 61 of file i2c.h.
I2C_PINSEL
enum I2C_PINSEL
I2C's pin modes.
Enumerator
I2C1_PINSEL
Pin mode for I2C1.
I2C2_PINSEL
Pin mode for I2C2.
Definition at line 71 of file i2c.h.
I2C_STATE
enum I2C_STATE
I2C device driver states.
Enumerator
I2C_IDLE
I2C_BUSY
Definition at line 90 of file i2c.h.
I2C_STATUS_MODE
enum I2C_STATUS_MODE
Different modes found in Status Register when an interruption is fired.
Enumerator
I2C_START
I2C_REPEATED_START
I2C_SLAW_ACK
I2C_SLAW_NACK
I2C_DATAW_ACK
I2C_DATAW_NACK
I2C_ARBITRATION_LOST
I2C_SLAR_ACK
I2C_SLAR_NACK
I2C_DATAR_ACK
I2C_DATAR_NACK
Definition at line 98 of file i2c.h.
Function Documentation
I2C1_Configure()
int I2C1_Configure (int frequency, int rSize, char * wBuffer, int wSize)
Configures I2C1 interface.
Parameters
frequency -> Rate of I2C1 communication, in Hz.
rSize -> Size of data (in bytes) to read.
wBuffer -> Data to write.
wSize -> Size of data (in bytes) to write.
Returns
0 if successful, -1 if timed out.
Definition at line 293 of file i2c.c.
Referenced by EEPROM_Read(), and EEPROM_Write().
I2C1_Engine()
int I2C1_Engine ()
Synchronously waits for the transmission on interface I2C1 to end.
Note
This is a blocking function.
Definition at line 362 of file i2c.c.
References STA.
Referenced by EEPROM_Read(), and EEPROM_Write().
I2C1_GetBuffer()
void I2C1_GetBuffer (char * buffer)
Copy data in read buffer on IC1 interface to specified pointer.
Parameters
buffer -> Specified pointer where data should be copied to.
Definition at line 396 of file i2c.c.
Referenced by EEPROM_Read().
I2C1_Init()
void I2C1_Init ()
Initialises I2C1 interface.
Note
Must be called prior to all other I2C1 functions.
Definition at line 243 of file i2c.c.
References I2C1_PCONP_ENABLE, I2C1_PINSEL, SYS, and WAIT_Init().
Referenced by EEPROM_Init().
I2C1_Start()
int I2C1_Start ()
Start a transmission in I2C1 interface (read or write).
Returns
0 if successful, -1 if timed out.
Definition at line 323 of file i2c.c.
References STA, and WAIT_SYS_GetElapsedMs().
Referenced by EEPROM_Read(), and EEPROM_Write().
I2C1_Stop()
void I2C1_Stop ()
Ends a started transmission on interface I2C1.
Definition at line 344 of file i2c.c.
References SI, and STO.
Referenced by EEPROM_Read(), and EEPROM_Write().
I2C2_Configure()
int I2C2_Configure (int frequency, int rSize, char * wBuffer, int wSize)
Configures I2C2 interface.
Parameters
frequency -> Rate of I2C2 communication, in Hz.
rSize -> Size of data (in bytes) to read.
wBuffer -> Data to write.
wSize -> Size of data (in bytes) to write.
Returns
0 if successful, -1 if timed out.
Definition at line 308 of file i2c.c.
I2C2_Engine()
int I2C2_Engine ()
Synchronously waits for the transmission on interface I2C2 to end.
Note
This is a blocking function.
Definition at line 379 of file i2c.c.
References STA.
I2C2_GetBuffer()
void I2C2_GetBuffer (char * buffer)
Copy data in read buffer on IC2 interface to specified pointer.
Parameters
buffer -> Specified pointer where data should be copied to.
Definition at line 400 of file i2c.c.
I2C2_Init()
void I2C2_Init ()
Initialises I2C2 interface.
Note
Must be called prior to all other I2C2 functions.
Definition at line 268 of file i2c.c.
References I2C2_PCONP_ENABLE, I2C2_PINSEL, SYS, and WAIT_Init().
I2C2_Start()
int I2C2_Start ()
Start a transmission in I2C2 interface (read or write).
Returns
0 if successful, -1 if timed out.
Definition at line 333 of file i2c.c.
References STA, and WAIT_SYS_GetElapsedMs().
I2C2_Stop()
void I2C2_Stop ()
Ends a started transmission on interface I2C2.
Definition at line 353 of file i2c.c.
References SI, and STO.