Car Runner in RTOS environment: C:/Users/pedro/Desktop/Projetos/G9_CAR_RUNNER_RTOS/Car_Runner_RTOS/src/car_runner_rtos.c File Reference
car_runner_rtos.c File Reference
#include "car_runner_rtos.h"
Functions
int main (void)
void taskSTATE_MACHINE (void *pvParameters)
Task to run application state machine.
void taskPOINTS (void *pvParameters)
Task to increment points variable, every POINTS_RATE ms.
void taskFUEL (void *pvParameters)
Task to decrement fuel, every FUEL_RATE ms.
void taskDATE (void *pvParameters)
Task to periodically get date from RTC, and overwrite queueDATE with the most recent object.
void taskSCORE_COUNT (void *pvParameters)
Task to increment scoreCount, every SCORE_SHOW_TIME ms. This variable indicates which score should be showing in idle mode.
void taskBLINK (void *pvParameters)
Task to invert blinked value, every HIGHLIGHT_BLINK_TIME ms. This variable indicates which score should be showing in idle mode.
void taskUPDATE_GAME (void *pvParameters)
Task to run game. Waits for user input (from ADXL) and updates LCD.
void taskNETWORK_MANAGER (void *pvParameters)
Task to manage Network functionalities.
void getUsername (void)
Prompts an input interface to the LCD, so the user can enter his name.
void printDateTime (RTC_TIME_FIELD without)
Receive current Date Time from queueDATE, and print to LCD.
void printScore (Score *score, int n)
Will print specified Score to the LCD.
void idle (void)
Idle Mode. The fundamental state of the program. Shows RTC time and best scores, alternately.
void printToCol (int col, unsigned char c1, unsigned char c2)
Print to an LCD column.
void shiftFuelIndicator (int *currentFuelCol)
Shift fuel indicator in LCD.
void shiftCar (CAR *car)
Shifts the whole car (i.e. front and back) 1 LCD column to the right.
void randomiseFuel (int from, int to, int map[LCD_DISPLAY_ROWS][LCD_DDRAM_LENGTH])
Randomises a unique fuel galleon in a specified range of the LCD DDRAM. Also updates array 'o' with such information.
void randomiseObstacles (int from, int to, int map[LCD_DISPLAY_ROWS][LCD_DDRAM_LENGTH])
Randomises new obstacles in a specified range of the LCD DDRAM. Also updates array 'o' with such information.
void checkForFuelGrab (CAR *car, int map[LCD_DISPLAY_ROWS][LCD_DDRAM_LENGTH])
Checks if any part of the Car (i.e. front or body) has hit a fuel galleon.
bool checkForLoss (CAR *car, int map[LCD_DISPLAY_ROWS][LCD_DDRAM_LENGTH])
Checks if any part of the Car (i.e. front or body) has hit a obstacle.
void explodeCar (CAR *car)
Animate explosion in car position.
void pregame (void)
State to wait for user to ready up.
void game (void)
State that runs the actual game.
void postgame (void)
State to show user's score.
void config (void)
State in which the user can configure some features.
void timeConfig (void)
State in which the user may configure RTC time.
void scoresErased (void)
State that tells the user the scores were erased.
bool yesOrNo (void(*f)(void))
Prompts the user with a 'Yes or No' interface, and runs the specified function if 'Yes' option is selected.
void vApplicationStackOverflowHook (TaskHandle_t pxTask, char *pcTaskName)
void vConfigureTimerForRunTimeStats (void)
Variables
SemaphoreHandle_t semGAME_END = NULL
SemaphoreHandle_t semPOINTS = NULL
SemaphoreHandle_t semFUEL = NULL
QueueHandle_t queueACC = NULL
QueueHandle_t queueUPDATE_GAME = NULL
QueueHandle_t queueDATE = NULL
Function Documentation
main()
int main (void)
Semaphores:
Queues:
Tasks:
Start
Definition at line 119 of file car_runner_rtos.c.
References BARRIER_CHAR, barrier_charmap, CAR_BACK_CHAR, car_back_charmap, CAR_FRONT_CHAR, car_front_charmap, EEPROM, FUEL1_CHAR, fuel1_charmap, FUEL2_CHAR, fuel2_charmap, FUEL3_CHAR, fuel3_charmap, FUEL4_CHAR, fuel4_charmap, FUEL_CHAR, fuel_charmap, printf(), queueDATE, queueUPDATE_GAME, SCORE_Init(), semFUEL, semGAME_END, semPOINTS, TASK_BLINK_PRIORITY, TASK_BLINK_STACK_SIZE, TASK_DATE_PRIORITY, TASK_DATE_STACK_SIZE, TASK_FUEL_PRIORITY, TASK_FUEL_STACK_SIZE, TASK_NETWORK_MANAGER_PRIORITY, TASK_NETWORK_MANAGER_STACK_SIZE, TASK_POINTS_PRIORITY, TASK_POINTS_STACK_SIZE, TASK_SCORE_COUNT_PRIORITY, TASK_SCORE_COUNT_STACK_SIZE, TASK_STATE_MACHINE_PRIORITY, TASK_STATE_MACHINE_STACK_SIZE, TASK_UPDATE_GAME_PRIORITY, TASK_UPDATE_GAME_STACK_SIZE, taskBLINK(), taskDATE(), taskFUEL(), taskNETWORK_MANAGER(), taskPOINTS(), taskSCORE_COUNT(), taskSTATE_MACHINE(), and taskUPDATE_GAME().
vApplicationStackOverflowHook()
void vApplicationStackOverflowHook (TaskHandle_t pxTask, char * pcTaskName)
Definition at line 1205 of file car_runner_rtos.c.
vConfigureTimerForRunTimeStats()
void vConfigureTimerForRunTimeStats (void)
Definition at line 1217 of file car_runner_rtos.c.
References configCPU_CLOCK_HZ.
Variable Documentation
queueACC
QueueHandle_t queueACC = NULL
Holds a signed short representing current inclination.
Definition at line 95 of file car_runner_rtos.c.
queueDATE
QueueHandle_t queueDATE = NULL
Holds a uint8_t dummy value.
Definition at line 105 of file car_runner_rtos.c.
Referenced by main(), printDateTime(), and taskDATE().
queueUPDATE_GAME
QueueHandle_t queueUPDATE_GAME = NULL
Holds a GAME_INFO structure.
Definition at line 100 of file car_runner_rtos.c.
Referenced by main(), and taskUPDATE_GAME().
semFUEL
SemaphoreHandle_t semFUEL = NULL
Binary semaphore to control access to global state.
Definition at line 78 of file car_runner_rtos.c.
Referenced by checkForFuelGrab(), main(), and taskFUEL().
semGAME_END
SemaphoreHandle_t semGAME_END = NULL
Binary semaphore to control access to global state.
Definition at line 68 of file car_runner_rtos.c.
Referenced by game(), and main().
semPOINTS
SemaphoreHandle_t semPOINTS = NULL
Binary semaphore to control access to global state.
Definition at line 73 of file car_runner_rtos.c.
Referenced by main(), taskPOINTS(), and taskUPDATE_GAME().