Embedded Systems Library: WAIT Public Functions
WAIT Public Functions
WAIT
Macros
#define TIMER_PCLK (SystemCoreClock/4)
PCLK.
#define TIMER_RES 0.000001
Timer resolution (1us).
#define TIMER_IR_MR0 0x1
Interrupt Register Mask.
#define SYSTICK_FREQ (SystemCoreClock / 1000)
Systick Frequency.
Enumerations
enum WAIT {
SYS, TIM0, IRQ0, TIM1,
IRQ1, TIM2, IRQ2, TIM3,
IRQ3
}
Type of resource to use in WAIT API.
enum TIMER_TCR { RESET = 0x3, DISABLE_RESET = 0x2, ENABLE = 0x1, DISABLE = 0x0 }
Timer Control Register modes.
enum TIMER_ENABLE { PCONP_ENABLE_TIM0 = (1<<1), PCONP_ENABLE_TIM1 = (1<<2), PCONP_ENABLE_TIM2 = (1<<22), PCONP_ENABLE_TIM3 = (1<<23) }
Enable PCONP bit for all timers.
enum TIMER_PCLK_BITS { BITS_PCLK_TIM0 = (0x03 << 2), BITS_PCLK_TIM1 = (0x03 << 4), BITS_PCLK_TIM2 = (0x03 << 12), BITS_PCLK_TIM3 = (0x03 << 14) }
PCLK Mask for all timers.
Functions
int32_t WAIT_Init (WAIT mode)
Initialises the wait API, using the desired resource.
void WAIT_SYS_Ms (uint32_t millis)
Waits a number of milliseconds.
void WAIT_TIM0_Us (uint32_t micros)
Waits a number of milliseconds.
void WAIT_IRQ0_Us (uint32_t micros, void(*f)(void))
Interrupts after a certain amount of us and executes a certain function.
void WAIT_TIM1_Us (uint32_t micros)
Waits a number of milliseconds.
void WAIT_IRQ1_Us (uint32_t micros, void(*f)(void))
Interrupts after a certain amount of us and executes a certain function.
void WAIT_TIM2_Us (uint32_t micros)
Waits a number of milliseconds.
void WAIT_IRQ2_Us (uint32_t micros, void(*f)(void))
Interrupts after a certain amount of us and executes a certain function.
void WAIT_TIM3_Us (uint32_t micros)
Waits a number of milliseconds.
void WAIT_IRQ3_Us (uint32_t micros, void(*f)(void))
Interrupts after a certain amount of us and executes a certain function.
bool WAIT_IsBusy (WAIT timer)
Ask if a specified timer is busy (waiting to interrupt).
uint32_t WAIT_SYS_GetElapsedMs (uint32_t start)
Get difference in milliseconds from parameter.
Detailed Description
Macro Definition Documentation
SYSTICK_FREQ
#define SYSTICK_FREQ (SystemCoreClock / 1000)
Systick Frequency.
Definition at line 70 of file wait.h.
TIMER_IR_MR0
#define TIMER_IR_MR0 0x1
Interrupt Register Mask.
Note
We are using Match Register 0.
Definition at line 65 of file wait.h.
TIMER_PCLK
#define TIMER_PCLK (SystemCoreClock/4)
PCLK.
Note
We are using PCLK = 1/4*CCLK
Definition at line 54 of file wait.h.
TIMER_RES
#define TIMER_RES 0.000001
Timer resolution (1us).
Definition at line 59 of file wait.h.
Enumeration Type Documentation
TIMER_ENABLE
enum TIMER_ENABLE
Enable PCONP bit for all timers.
Enumerator
PCONP_ENABLE_TIM0
PCONP Enable bit for timer0.
PCONP_ENABLE_TIM1
PCONP Enable bit for timer1.
PCONP_ENABLE_TIM2
PCONP Enable bit for timer2.
PCONP_ENABLE_TIM3
PCONP Enable bit for timer3.
Definition at line 102 of file wait.h.
TIMER_PCLK_BITS
enum TIMER_PCLK_BITS
PCLK Mask for all timers.
Enumerator
BITS_PCLK_TIM0
PCLK Mask for timer0 -> bits [3:2].
BITS_PCLK_TIM1
PCLK Mask for timer1 -> bits [5:4].
BITS_PCLK_TIM2
PCLK Mask for timer2 -> bits [13:12].
BITS_PCLK_TIM3
PCLK Mask for timer3 -> bits [15:14].
Definition at line 114 of file wait.h.
TIMER_TCR
enum TIMER_TCR
Timer Control Register modes.
Enumerator
RESET
Reset TC.
DISABLE_RESET
Reset and disable TC.
ENABLE
Enable TC.
DISABLE
Disable TC.
Definition at line 91 of file wait.h.
WAIT
enum WAIT
Type of resource to use in WAIT API.
Enumerator
SYS
to use the SYSTICK resource.
TIM0
to use the TIMER resource of timer0.
IRQ0
to use the IRQ (Interrupt Request) resource of timer0.
TIM1
to use the TIMER resource of timer1.
IRQ1
to use the IRQ (Interrupt Request) resource of timer1.
TIM2
to use the TIMER resource of timer2.
IRQ2
to use the IRQ (Interrupt Request) resource of timer2.
TIM3
to use the TIMER resource of timer3.
IRQ3
to use the IRQ (Interrupt Request) resource of timer3.
Definition at line 75 of file wait.h.
Function Documentation
WAIT_Init()
int32_t WAIT_Init (WAIT mode)
Initialises the wait API, using the desired resource.
Parameters
mode -> Which resource to use (see enum WAIT).
Returns
0 if initialisation successed, -1 if fails.
Note
This function must be called prior to any other WAIT functions.
Only 1 type of resource may be initialised for each timer, i.e. if TIMi is initialised, trying to initialise IRQi will fail, and vice-versa.
Definition at line 82 of file wait.c.
Referenced by BUTTON_Init(), ESP_Init(), I2C1_Init(), I2C2_Init(), and LCDText_Init().
WAIT_IRQ0_Us()
void WAIT_IRQ0_Us (uint32_t micros, void(*)(void) f)
Interrupts after a certain amount of us and executes a certain function.
Note
Requires Interrupt Request Handler Initialisation [IRQ] for timer0.
Parameters
micros -> The whole number of microseconds to wait.
f : -> Function to be executed upon interrupt.
Definition at line 281 of file wait.c.
WAIT_IRQ1_Us()
void WAIT_IRQ1_Us (uint32_t micros, void(*)(void) f)
Interrupts after a certain amount of us and executes a certain function.
Note
Requires Interrupt Request Handler Initialisation [IRQ] for timer1.
Parameters
micros -> The whole number of microseconds to wait.
f : -> Function to be executed upon interrupt.
Definition at line 302 of file wait.c.
WAIT_IRQ2_Us()
void WAIT_IRQ2_Us (uint32_t micros, void(*)(void) f)
Interrupts after a certain amount of us and executes a certain function.
Note
Requires Interrupt Request Handler Initialisation [IRQ] for timer2.
Parameters
micros -> The whole number of microseconds to wait.
f : -> Function to be executed upon interrupt.
Definition at line 323 of file wait.c.
WAIT_IRQ3_Us()
void WAIT_IRQ3_Us (uint32_t micros, void(*)(void) f)
Interrupts after a certain amount of us and executes a certain function.
Note
Requires Interrupt Request Handler Initialisation [IRQ] for timer3.
Parameters
micros -> The whole number of microseconds to wait.
f : -> Function to be executed upon interrupt.
Definition at line 344 of file wait.c.
WAIT_IsBusy()
bool WAIT_IsBusy (WAIT timer)
Ask if a specified timer is busy (waiting to interrupt).
Parameters
timer -> Timer requested.
Returns
True if requested timer is busy, false if not.
Definition at line 353 of file wait.c.
References TIM0.
WAIT_SYS_GetElapsedMs()
uint32_t WAIT_SYS_GetElapsedMs (uint32_t start)
Get difference in milliseconds from parameter.
Note
Requires SYSTICK Initialisation [SYS].
Parameters
start -> if 0 get current milliseconds.
Returns
Elapsed ms since start.
Definition at line 376 of file wait.c.
Referenced by I2C1_Start(), and I2C2_Start().
WAIT_SYS_Ms()
void WAIT_SYS_Ms (uint32_t millis)
Waits a number of milliseconds.
Note
Requires SYSTICK Initialisation [SYS].
Parameters
millis -> The whole number of milliseconds to wait.
Definition at line 257 of file wait.c.
Referenced by EEPROM_Write(), and ESP_Init().
WAIT_TIM0_Us()
void WAIT_TIM0_Us (uint32_t micros)
Waits a number of milliseconds.
Note
Requires TIMER0 Initialisation [TIM].
Parameters
micros -> The whole number of microseconds to wait.
Definition at line 269 of file wait.c.
References DISABLE_RESET, ENABLE, and TIMER_IR_MR0.
WAIT_TIM1_Us()
void WAIT_TIM1_Us (uint32_t micros)
Waits a number of milliseconds.
Note
Requires TIMER1 Initialisation [TIM].
Parameters
micros -> The whole number of microseconds to wait.
Definition at line 290 of file wait.c.
References DISABLE_RESET, ENABLE, and TIMER_IR_MR0.
WAIT_TIM2_Us()
void WAIT_TIM2_Us (uint32_t micros)
Waits a number of milliseconds.
Note
Requires TIMER2 Initialisation [TIM].
Parameters
micros -> The whole number of microseconds to wait.
Definition at line 311 of file wait.c.
References DISABLE_RESET, ENABLE, and TIMER_IR_MR0.
WAIT_TIM3_Us()
void WAIT_TIM3_Us (uint32_t micros)
Waits a number of milliseconds.
Note
Requires TIMER3 Initialisation [TIM].
Parameters
micros -> The whole number of microseconds to wait.
Definition at line 332 of file wait.c.
References DISABLE_RESET, ENABLE, and TIMER_IR_MR0.
Referenced by LCDText_Init().