Embedded Systems Library: C:/Users/pedro/Desktop/Projetos/G9_CAR_RUNNER_RTOS/LEETC_SE1/inc/transport.h File Reference
transport.h File Reference
Data Structures
struct transport_iofunctions_t
Macros
#define TRANSPORT_DONE 1
#define TRANSPORT_AGAIN 0
#define TRANSPORT_ERROR -1
Functions
int transport_sendPacketBuffer (int sock, unsigned char *buf, int buflen)
int transport_getdata (unsigned char *buf, int count)
void transport_sendPacketBuffernb_start (int sock, unsigned char *buf, int buflen)
int transport_sendPacketBuffernb (int sock)
int transport_getdatanb (void *sck, unsigned char *buf, int count)
int transport_open (transport_iofunctions_t *thisio)
int transport_close (int sock)
Macro Definition Documentation
TRANSPORT_AGAIN
#define TRANSPORT_AGAIN 0
Definition at line 23 of file transport.h.
TRANSPORT_DONE
#define TRANSPORT_DONE 1
Definition at line 22 of file transport.h.
TRANSPORT_ERROR
#define TRANSPORT_ERROR -1
Definition at line 24 of file transport.h.
Function Documentation
transport_close()
int transport_close (int sock)
Definition at line 116 of file transport.c.
References TRANSPORT_DONE.
transport_getdata()
int transport_getdata (unsigned char * buf, int count)
Note
Blocks until requested count is received, as MQTTPacket_read() expects
Warning
This function is not supported (not implemented)
unless you provide a timeout, this function can block forever. Socket based systems do have a built in timeout, if your system can provide this, do modify this function, otherwise use getdatanb() instead
Returns
number of bytes read
Definition at line 82 of file transport.c.
References TRANSPORT_ERROR.
transport_getdatanb()
int transport_getdatanb (void * sck, unsigned char * buf, int count)
This is a bare metal implementation, so we must have non-blocking functions, the process of sucking from serial lines can result a bit slow and we don't want to busy wait
Returns
the actual number of bytes read, 0 for none, or TRANSPORT_ERROR on error
Note
you will call again until total number of expected bytes is read (this is stream)
Definition at line 88 of file transport.c.
transport_open()
int transport_open (transport_iofunctions_t * thisio)
We assume whatever connection needs to be done, it is externally established by the specifics of the hardware E.g.: A cell modem: you will call AT+whatever and put the modem in transparent mode, OR, you will embed the AT+xSENDx / AT+xRECVx commands into the former sendPacketBuffer() and getdatanb() functions
Parameters
thisio pointer to a structure containing all necessary stuff to handle direct serial I/O
Returns
whatever indicator the system assigns to this link, if any. (a.k.a. : 'sock'), or TRANSPORT_ERROR for error
return >=0 for a connection descriptor, <0 for an error code
Definition at line 106 of file transport.c.
transport_sendPacketBuffer()
int transport_sendPacketBuffer (int sock, unsigned char * buf, int buflen)
Note
Blocks until requested buflen is sent
Definition at line 67 of file transport.c.
References TRANSPORT_AGAIN, TRANSPORT_DONE, TRANSPORT_ERROR, transport_sendPacketBuffernb(), and transport_sendPacketBuffernb_start().
transport_sendPacketBuffernb()
int transport_sendPacketBuffernb (int sock)
This is a bare metal implementation, so we must have non-blocking functions, the process of pumping to serial lines can result a bit slow and we don't want to busy wait
Returns
TRANSPORT_DONE if finished, TRANSPORT_AGAIN for call again, or TRANSPORT_ERROR on error
Note
you will call again until it finishes (this is stream)
Definition at line 48 of file transport.c.
Referenced by transport_sendPacketBuffer().
transport_sendPacketBuffernb_start()
void transport_sendPacketBuffernb_start (int sock, unsigned char * buf, int buflen)
This is a bare metal implementation, so we must have non-blocking functions, the process of pumping to serial lines can result a bit slow and we don't want to busy wait. This function starts the process, you will call sendPacketBuffernb() until it reports success (or error)
Definition at line 42 of file transport.c.
Referenced by transport_sendPacketBuffer().