Embedded Systems Library: C:/Users/pedro/Desktop/Projetos/G9_CAR_RUNNER_RTOS/LEETC_SE1/src/transport.c File Reference
transport.c File Reference
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <assert.h>
#include "transport.h"
Functions
void transport_sendPacketBuffernb_start (int sock, unsigned char *buf, int buflen)
int transport_sendPacketBuffernb (int sock)
int transport_sendPacketBuffer (int sock, unsigned char *buf, int buflen)
int transport_getdata (unsigned char *buf, int count)
int transport_getdatanb (void *sck, unsigned char *buf, int count)
int transport_open (transport_iofunctions_t *thisio)
int transport_close (int sock)
Function Documentation
transport_close()
int transport_close (int sock)
Definition at line 116 of file transport.c.
References TRANSPORT_DONE.
transport_getdata()
int transport_getdata (unsigned char * buf, int count)
Note
Blocks until requested count is received, as MQTTPacket_read() expects
Warning
This function is not supported (not implemented)
unless you provide a timeout, this function can block forever. Socket based systems do have a built in timeout, if your system can provide this, do modify this function, otherwise use getdatanb() instead
Returns
number of bytes read
Definition at line 82 of file transport.c.
References TRANSPORT_ERROR.
transport_getdatanb()
int transport_getdatanb (void * sck, unsigned char * buf, int count)
This is a bare metal implementation, so we must have non-blocking functions, the process of sucking from serial lines can result a bit slow and we don't want to busy wait
Returns
the actual number of bytes read, 0 for none, or TRANSPORT_ERROR on error
Note
you will call again until total number of expected bytes is read (this is stream)
Definition at line 88 of file transport.c.
transport_open()
int transport_open (transport_iofunctions_t * thisio)
return >=0 for a connection descriptor, <0 for an error code
Definition at line 106 of file transport.c.
transport_sendPacketBuffer()
int transport_sendPacketBuffer (int sock, unsigned char * buf, int buflen)
Note
Blocks until requested buflen is sent
Definition at line 67 of file transport.c.
References TRANSPORT_AGAIN, TRANSPORT_DONE, TRANSPORT_ERROR, transport_sendPacketBuffernb(), and transport_sendPacketBuffernb_start().
transport_sendPacketBuffernb()
int transport_sendPacketBuffernb (int sock)
This is a bare metal implementation, so we must have non-blocking functions, the process of pumping to serial lines can result a bit slow and we don't want to busy wait
Returns
TRANSPORT_DONE if finished, TRANSPORT_AGAIN for call again, or TRANSPORT_ERROR on error
Note
you will call again until it finishes (this is stream)
Definition at line 48 of file transport.c.
Referenced by transport_sendPacketBuffer().
transport_sendPacketBuffernb_start()
void transport_sendPacketBuffernb_start (int sock, unsigned char * buf, int buflen)
This is a bare metal implementation, so we must have non-blocking functions, the process of pumping to serial lines can result a bit slow and we don't want to busy wait. This function starts the process, you will call sendPacketBuffernb() until it reports success (or error)
Definition at line 42 of file transport.c.
Referenced by transport_sendPacketBuffer().