Car Runner in RTOS environment: CAR_RUNNER_RTOS Public Functions
CAR_RUNNER_RTOS Public Functions
CAR_RUNNER_RTOS
Data Structures
struct CAR
Structure that will hold the Car's current location on the LCD.
struct GAME_INFO
Idle mode for Idle Task:
struct DATE_TIME
Date Time String Struct.
Macros
#define TASK_ACC_PRIORITY tskIDLE_PRIORITY + 1
#define TASK_DATE_PRIORITY tskIDLE_PRIORITY + 1
#define TASK_POINTS_PRIORITY tskIDLE_PRIORITY + 1
#define TASK_STATE_MACHINE_PRIORITY tskIDLE_PRIORITY + 1
#define TASK_SCORE_COUNT_PRIORITY tskIDLE_PRIORITY + 1
#define TASK_UPDATE_GAME_PRIORITY tskIDLE_PRIORITY + 1
#define TASK_FUEL_PRIORITY tskIDLE_PRIORITY + 1
#define TASK_BLINK_PRIORITY tskIDLE_PRIORITY + 1
#define TASK_NETWORK_MANAGER_PRIORITY tskIDLE_PRIORITY + 1
#define TASK_ACC_STACK_SIZE configMINIMAL_STACK_SIZE*1
#define TASK_DATE_STACK_SIZE configMINIMAL_STACK_SIZE*2
#define TASK_POINTS_STACK_SIZE configMINIMAL_STACK_SIZE*0.5
#define TASK_STATE_MACHINE_STACK_SIZE configMINIMAL_STACK_SIZE*3
#define TASK_SCORE_COUNT_STACK_SIZE configMINIMAL_STACK_SIZE*0.5
#define TASK_UPDATE_GAME_STACK_SIZE configMINIMAL_STACK_SIZE*5
#define TASK_FUEL_STACK_SIZE configMINIMAL_STACK_SIZE*0.5
#define TASK_BLINK_STACK_SIZE configMINIMAL_STACK_SIZE*0.5
#define TASK_NETWORK_MANAGER_STACK_SIZE configMINIMAL_STACK_SIZE*2
#define CONFIG_OPTIONS 3
Number of entries in Configuration Mode menu.
#define TIME_CONFIG_FIELDS 6
Number of time fields to configure in Time Configuration Mode.
#define BUTTONS_HOLD_TIME 2000
Necessary time to hold buttons, in order to enter/exit Configuration Mode.
#define SCORE_SHOW_TIME 3000
Time between different scores being displayed, in Idle Mode.
#define HIGHLIGHT_BLINK_TIME 300
Blinking time, used to highlight fields.
#define POINTS_RATE 1000
Points increment rate, in Game Mode.
#define GAME_RATE 300
Game update rate (i.e. time in us between each "frame"), in Game Mode.
#define FUEL_RATE 2000
Fuel tank decrement rate, in Game Mode.
#define CAR_POSITION 3
Column in which user will visualise the car (should be < 10).
#define INITIAL_OBSTACLE_GAP CAR_POSITION + 5
Columns with no obstacles as of starting the game.
#define MAX_FUEL 8
Maximum fuel.
#define INCLINATION_THRESHOLD 60
Value ADXL345's Y-Axis needs to surpass, to count as row change.
#define CAR_BACK_CHAR 0
LCD special char for Car Back.
#define CAR_FRONT_CHAR 1
LCD special char for Car Front.
#define BARRIER_CHAR 2
LCD special char for Barrier.
#define FUEL_CHAR 3
LCD special char for Fuel Galleon.
#define FUEL1_CHAR 4
LCD special char for Fuel indicator at 1/4.
#define FUEL2_CHAR 5
LCD special char for Fuel indicator at 2/4.
#define FUEL3_CHAR 6
LCD special char for Fuel indicator at 3/4.
#define FUEL4_CHAR 7
LCD special char for Fuel indicator at 4/4.
#define SSID "NOS-1360"
Access Point SSID to connect to.
#define PASS "HPW572MH"
Password to SSID.
Enumerations
enum STATE {
STATE_IDLE = 0, STATE_CONFIG = 1, STATE_CONFIG_DATE = 2, STATE_CONFIG_NAME = 3,
STATE_CONFIG_ERASE_SCORES = 4, STATE_SCORES_ERASED = 5, STATE_PREGAME = 6, STATE_INGAME = 7,
STATE_POSTGAME = 8
}
States of the state machine:
enum IDLE_MODE { IDLE_SHOW_DATE, IDLE_SHOW_SCORES }
Idle mode for Idle Task:
Functions
void taskDATE (void *pvParameters)
Task to periodically get date from RTC, and overwrite queueDATE with the most recent object.
void taskPOINTS (void *pvParameters)
Task to increment points variable, every POINTS_RATE ms.
void taskSTATE_MACHINE (void *pvParameters)
Task to run application state machine.
void taskSCORE_COUNT (void *pvParameters)
Task to increment scoreCount, every SCORE_SHOW_TIME ms. This variable indicates which score should be showing in idle mode.
void taskUPDATE_GAME (void *pvParameters)
Task to run game. Waits for user input (from ADXL) and updates LCD.
void taskFUEL (void *pvParameters)
Task to decrement fuel, every FUEL_RATE ms.
void taskBLINK (void *pvParameters)
Task to invert blinked value, every HIGHLIGHT_BLINK_TIME ms. This variable indicates which score should be showing in idle mode.
void taskNETWORK_MANAGER (void *pvParameters)
Task to manage Network functionalities.
void getUsername (void)
Prompts an input interface to the LCD, so the user can enter his name.
void printDateTime (RTC_TIME_FIELD without)
Receive current Date Time from queueDATE, and print to LCD.
void printScore (Score *score, int n)
Will print specified Score to the LCD.
void idle (void)
Idle Mode. The fundamental state of the program. Shows RTC time and best scores, alternately.
void printToCol (int col, unsigned char c1, unsigned char c2)
Print to an LCD column.
void shiftFuelIndicator (int *currentFuelCol)
Shift fuel indicator in LCD.
void shiftCar (CAR *car)
Shifts the whole car (i.e. front and back) 1 LCD column to the right.
void randomiseFuel (int from, int to, int map[LCD_DISPLAY_ROWS][LCD_DDRAM_LENGTH])
Randomises a unique fuel galleon in a specified range of the LCD DDRAM. Also updates array 'o' with such information.
void randomiseObstacles (int from, int to, int map[LCD_DISPLAY_ROWS][LCD_DDRAM_LENGTH])
Randomises new obstacles in a specified range of the LCD DDRAM. Also updates array 'o' with such information.
void checkForFuelGrab (CAR *car, int map[LCD_DISPLAY_ROWS][LCD_DDRAM_LENGTH])
Checks if any part of the Car (i.e. front or body) has hit a fuel galleon.
bool checkForLoss (CAR *car, int map[LCD_DISPLAY_ROWS][LCD_DDRAM_LENGTH])
Checks if any part of the Car (i.e. front or body) has hit a obstacle.
void explodeCar (CAR *car)
Animate explosion in car position.
void pregame (void)
State to wait for user to ready up.
void game (void)
State that runs the actual game.
void postgame (void)
State to show user's score.
void config (void)
State in which the user can configure some features.
void timeConfig (void)
State in which the user may configure RTC time.
void scoresErased (void)
State that tells the user the scores were erased.
bool yesOrNo (void(*f)(void))
Prompts the user with a 'Yes or No' interface, and runs the specified function if 'Yes' option is selected.
Variables
const unsigned char car_back_charmap []
Char map for Car Back.
const unsigned char fuel_charmap []
Char map for Fuel Galleon.
const unsigned char car_front_charmap []
Char map for Car Front.
const unsigned char barrier_charmap []
Char map for Barrier.
const unsigned char fuel4_charmap []
Char map for 4/4 fuel indicator.
const unsigned char fuel3_charmap []
Char map for 3/4 fuel indicator.
const unsigned char fuel2_charmap []
Char map for 2/4 fuel indicator.
const unsigned char fuel1_charmap []
Char map for 1/4 fuel indicator.
Detailed Description
Macro Definition Documentation
BARRIER_CHAR
#define BARRIER_CHAR 2
LCD special char for Barrier.
Note
Shouldn't be changed.
Definition at line 252 of file car_runner_rtos.h.
BUTTONS_HOLD_TIME
#define BUTTONS_HOLD_TIME 2000
Necessary time to hold buttons, in order to enter/exit Configuration Mode.
Definition at line 188 of file car_runner_rtos.h.
CAR_BACK_CHAR
#define CAR_BACK_CHAR 0
LCD special char for Car Back.
Note
Shouldn't be changed.
Definition at line 240 of file car_runner_rtos.h.
CAR_FRONT_CHAR
#define CAR_FRONT_CHAR 1
LCD special char for Car Front.
Note
Shouldn't be changed.
Definition at line 246 of file car_runner_rtos.h.
CAR_POSITION
#define CAR_POSITION 3
Column in which user will visualise the car (should be < 10).
Definition at line 218 of file car_runner_rtos.h.
CONFIG_OPTIONS
#define CONFIG_OPTIONS 3
Number of entries in Configuration Mode menu.
Note
Shouldn't be changed.
Definition at line 177 of file car_runner_rtos.h.
FUEL1_CHAR
#define FUEL1_CHAR 4
LCD special char for Fuel indicator at 1/4.
Note
Shouldn't be changed.
Definition at line 264 of file car_runner_rtos.h.
FUEL2_CHAR
#define FUEL2_CHAR 5
LCD special char for Fuel indicator at 2/4.
Note
Shouldn't be changed.
Definition at line 270 of file car_runner_rtos.h.
FUEL3_CHAR
#define FUEL3_CHAR 6
LCD special char for Fuel indicator at 3/4.
Note
Shouldn't be changed.
Definition at line 276 of file car_runner_rtos.h.
FUEL4_CHAR
#define FUEL4_CHAR 7
LCD special char for Fuel indicator at 4/4.
Note
Shouldn't be changed.
Definition at line 282 of file car_runner_rtos.h.
FUEL_CHAR
#define FUEL_CHAR 3
LCD special char for Fuel Galleon.
Note
Shouldn't be changed.
Definition at line 258 of file car_runner_rtos.h.
FUEL_RATE
#define FUEL_RATE 2000
Fuel tank decrement rate, in Game Mode.
Definition at line 213 of file car_runner_rtos.h.
GAME_RATE
#define GAME_RATE 300
Game update rate (i.e. time in us between each "frame"), in Game Mode.
Definition at line 208 of file car_runner_rtos.h.
HIGHLIGHT_BLINK_TIME
#define HIGHLIGHT_BLINK_TIME 300
Blinking time, used to highlight fields.
Definition at line 198 of file car_runner_rtos.h.
INCLINATION_THRESHOLD
#define INCLINATION_THRESHOLD 60
Value ADXL345's Y-Axis needs to surpass, to count as row change.
Definition at line 234 of file car_runner_rtos.h.
INITIAL_OBSTACLE_GAP
#define INITIAL_OBSTACLE_GAP CAR_POSITION + 5
Columns with no obstacles as of starting the game.
Definition at line 223 of file car_runner_rtos.h.
MAX_FUEL
#define MAX_FUEL 8
Maximum fuel.
Note
Shouldn't be changed.
Definition at line 229 of file car_runner_rtos.h.
PASS
#define PASS "HPW572MH"
Password to SSID.
Definition at line 292 of file car_runner_rtos.h.
POINTS_RATE
#define POINTS_RATE 1000
Points increment rate, in Game Mode.
Definition at line 203 of file car_runner_rtos.h.
SCORE_SHOW_TIME
#define SCORE_SHOW_TIME 3000
Time between different scores being displayed, in Idle Mode.
Definition at line 193 of file car_runner_rtos.h.
SSID
#define SSID "NOS-1360"
Access Point SSID to connect to.
Definition at line 287 of file car_runner_rtos.h.
TASK_ACC_PRIORITY
#define TASK_ACC_PRIORITY tskIDLE_PRIORITY + 1
Includes
Note
Accelerometer Task Priority.
Definition at line 64 of file car_runner_rtos.h.
TASK_ACC_STACK_SIZE
#define TASK_ACC_STACK_SIZE configMINIMAL_STACK_SIZE*1
Note
Accelerometer Task Stack Size.
Definition at line 121 of file car_runner_rtos.h.
TASK_BLINK_PRIORITY
#define TASK_BLINK_PRIORITY tskIDLE_PRIORITY + 1
Note
Blink Task Priority.
Definition at line 99 of file car_runner_rtos.h.
TASK_BLINK_STACK_SIZE
#define TASK_BLINK_STACK_SIZE configMINIMAL_STACK_SIZE*0.5
Note
Blink Task Stack Size.
Definition at line 156 of file car_runner_rtos.h.
TASK_DATE_PRIORITY
#define TASK_DATE_PRIORITY tskIDLE_PRIORITY + 1
Note
Date Task Priority.
Definition at line 69 of file car_runner_rtos.h.
TASK_DATE_STACK_SIZE
#define TASK_DATE_STACK_SIZE configMINIMAL_STACK_SIZE*2
Note
Date Task Stack Size.
Definition at line 126 of file car_runner_rtos.h.
TASK_FUEL_PRIORITY
#define TASK_FUEL_PRIORITY tskIDLE_PRIORITY + 1
Note
Fuel Task Priority.
Definition at line 94 of file car_runner_rtos.h.
TASK_FUEL_STACK_SIZE
#define TASK_FUEL_STACK_SIZE configMINIMAL_STACK_SIZE*0.5
Note
Fuel Task Stack Size.
Definition at line 151 of file car_runner_rtos.h.
TASK_NETWORK_MANAGER_PRIORITY
#define TASK_NETWORK_MANAGER_PRIORITY tskIDLE_PRIORITY + 1
Note
Blink Task Priority.
Definition at line 104 of file car_runner_rtos.h.
TASK_NETWORK_MANAGER_STACK_SIZE
#define TASK_NETWORK_MANAGER_STACK_SIZE configMINIMAL_STACK_SIZE*2
Note
Blink Task Stack Size.
Definition at line 161 of file car_runner_rtos.h.
TASK_POINTS_PRIORITY
#define TASK_POINTS_PRIORITY tskIDLE_PRIORITY + 1
Note
Points Task Priority.
Definition at line 74 of file car_runner_rtos.h.
TASK_POINTS_STACK_SIZE
#define TASK_POINTS_STACK_SIZE configMINIMAL_STACK_SIZE*0.5
Note
Points Task Stack Size.
Definition at line 131 of file car_runner_rtos.h.
TASK_SCORE_COUNT_PRIORITY
#define TASK_SCORE_COUNT_PRIORITY tskIDLE_PRIORITY + 1
Note
Score Count Task Priority.
Definition at line 84 of file car_runner_rtos.h.
TASK_SCORE_COUNT_STACK_SIZE
#define TASK_SCORE_COUNT_STACK_SIZE configMINIMAL_STACK_SIZE*0.5
Note
Score Count Task Stack Size.
Definition at line 141 of file car_runner_rtos.h.
TASK_STATE_MACHINE_PRIORITY
#define TASK_STATE_MACHINE_PRIORITY tskIDLE_PRIORITY + 1
Note
State Machine Task Priority.
Definition at line 79 of file car_runner_rtos.h.
TASK_STATE_MACHINE_STACK_SIZE
#define TASK_STATE_MACHINE_STACK_SIZE configMINIMAL_STACK_SIZE*3
Note
State Machine Task Stack Size.
Definition at line 136 of file car_runner_rtos.h.
TASK_UPDATE_GAME_PRIORITY
#define TASK_UPDATE_GAME_PRIORITY tskIDLE_PRIORITY + 1
Note
Update Game Task Priority.
Definition at line 89 of file car_runner_rtos.h.
TASK_UPDATE_GAME_STACK_SIZE
#define TASK_UPDATE_GAME_STACK_SIZE configMINIMAL_STACK_SIZE*5
Note
Update Game Task Stack Size.
Definition at line 146 of file car_runner_rtos.h.
TIME_CONFIG_FIELDS
#define TIME_CONFIG_FIELDS 6
Number of time fields to configure in Time Configuration Mode.
Note
Shouldn't be changed.
Definition at line 183 of file car_runner_rtos.h.
Enumeration Type Documentation
IDLE_MODE
enum IDLE_MODE
Idle mode for Idle Task:
Enumerator
IDLE_SHOW_DATE
Idle task showing date.
IDLE_SHOW_SCORES
Idle task showing score.
Definition at line 325 of file car_runner_rtos.h.
STATE
enum STATE
States of the state machine:
Enumerator
STATE_IDLE
Main menu.
STATE_CONFIG
Configuration menu.
STATE_CONFIG_DATE
Date configuration.
STATE_CONFIG_NAME
Name configuration.
STATE_CONFIG_ERASE_SCORES
Clear scores.
STATE_SCORES_ERASED
Screen indicating scores were erased.
STATE_PREGAME
Screen that waits for user to ready up.
STATE_INGAME
Actual game.
STATE_POSTGAME
Screen that shows user's score.
Definition at line 309 of file car_runner_rtos.h.
Function Documentation
checkForFuelGrab()
void checkForFuelGrab (CAR * car, int map[LCD_DISPLAY_ROWS][LCD_DDRAM_LENGTH])
Checks if any part of the Car (i.e. front or body) has hit a fuel galleon.
Parameters
car -> Pointer to Car.
map -> Array representing all objects currently in LCD DDRAM (2 for fuel galleon, 1 for obstacle, 0 for nothing).
Note
If a galleon has been hit, fuel is added to the fuel indicator.
Definition at line 900 of file car_runner_rtos.c.
References CAR::back_column, CAR::row, and semFUEL.
checkForLoss()
bool checkForLoss (CAR * car, int map[LCD_DISPLAY_ROWS][LCD_DDRAM_LENGTH])
Checks if any part of the Car (i.e. front or body) has hit a obstacle.
Parameters
car -> Pointer to Car.
map -> Array representing all objects currently in LCD DDRAM (2 for fuel galleon, 1 for obstacle, 0 for nothing).
Returns
If an obstacle has been hit, returns true. Else, returns false.
Definition at line 917 of file car_runner_rtos.c.
References CAR::back_column, CAR::front_column, and CAR::row.
config()
void config (void)
State in which the user can configure some features.
Note
Use B1 and B2 to scroll through the different options.
Use B3 to select highlighted option.
This function never clears the LCD display.
Definition at line 984 of file car_runner_rtos.c.
explodeCar()
void explodeCar (CAR * car)
Animate explosion in car position.
Parameters
car -> Pointer to Car.
Definition at line 921 of file car_runner_rtos.c.
References CAR::back_column, CAR::front_column, and CAR::row.
game()
void game (void)
State that runs the actual game.
Note
Tilt the ADXL345 component to change the row the Car is on.
This function never clears the LCD display.
Definition at line 941 of file car_runner_rtos.c.
References GAME_INFO::init, and semGAME_END.
getUsername()
void getUsername (void)
Prompts an input interface to the LCD, so the user can enter his name.
Note
Use B1 and B2 to increment and decrement, respectively, each character field, using B3 to advance.
This function never clears the LCD display.
Definition at line 520 of file car_runner_rtos.c.
References NAME_LENGTH.
idle()
void idle (void)
Idle Mode. The fundamental state of the program. Shows RTC time and best scores, alternately.
Note
Use B1 and B2 to scroll between 'Time' and 'Best Scores'.
Use B3 to enter Game Mode.
Hold B1 and B2 for a certain amount of time to enter Configuration Mode.
This function never clears the LCD display.
Definition at line 698 of file car_runner_rtos.c.
postgame()
void postgame (void)
State to show user's score.
Note
Hit any button to go to menu.
Definition at line 962 of file car_runner_rtos.c.
pregame()
void pregame (void)
State to wait for user to ready up.
Note
Hit any button to start the game.
Definition at line 929 of file car_runner_rtos.c.
printDateTime()
void printDateTime (RTC_TIME_FIELD without)
Receive current Date Time from queueDATE, and print to LCD.
Parameters
without -> Field to blink. If blink isn't wanted, NONE should be passed.
Note
This function never clears the LCD display.
Definition at line 587 of file car_runner_rtos.c.
References DATE_TIME::date, queueDATE, and DATE_TIME::time.
Referenced by timeConfig().
printScore()
void printScore (Score * score, int n)
Will print specified Score to the LCD.
Parameters
score -> Pointer to specified Score.
n -> Placement of score, starting at 0 (p.e. if 'score' is the second best, write 1).
Note
This function never clears the LCD display.
Definition at line 652 of file car_runner_rtos.c.
References Score::name, and Score::score.
printToCol()
void printToCol (int col, unsigned char c1, unsigned char c2)
Print to an LCD column.
Parameters
col -> Column where chars should be printed.
c1 -> Char to print in row 1.
c2 -> Char to print in row 2.
Definition at line 775 of file car_runner_rtos.c.
randomiseFuel()
void randomiseFuel (int from, int to, int map[LCD_DISPLAY_ROWS][LCD_DDRAM_LENGTH])
Randomises a unique fuel galleon in a specified range of the LCD DDRAM. Also updates array 'o' with such information.
Parameters
from -> Randomisation will start in this column.
to -> Randomisation will end in this column.
map -> Array representing all objects currently in LCD DDRAM (2 for fuel galleon, 1 for obstacle, 0 for nothing).
Note
Only places the fuel in a column where there's no obstacles in either row.
Definition at line 845 of file car_runner_rtos.c.
References FUEL_CHAR.
randomiseObstacles()
void randomiseObstacles (int from, int to, int map[LCD_DISPLAY_ROWS][LCD_DDRAM_LENGTH])
Randomises new obstacles in a specified range of the LCD DDRAM. Also updates array 'o' with such information.
Parameters
from -> Randomisation will start in this column.
to -> Randomisation will end in this column.
map -> Array representing all objects currently in LCD DDRAM (2 for fuel galleon, 1 for obstacle, 0 for nothing).
Note
A space of at least 2 columns is always left between each obstacle.
Definition at line 865 of file car_runner_rtos.c.
References BARRIER_CHAR.
scoresErased()
void scoresErased (void)
State that tells the user the scores were erased.
Note
Hit any button to go back.
This function never clears the LCD display.
Definition at line 1129 of file car_runner_rtos.c.
shiftCar()
void shiftCar (CAR * car)
Shifts the whole car (i.e. front and back) 1 LCD column to the right.
Parameters
car -> Pointer to Car.
Note
The LCD display is never shifted in this function. Only the car is shifted.
Definition at line 824 of file car_runner_rtos.c.
References CAR::back_column, CAR_BACK_CHAR, CAR_FRONT_CHAR, CAR::front_column, CAR::last_row, and CAR::row.
shiftFuelIndicator()
void shiftFuelIndicator (int * currentFuelCol)
Shift fuel indicator in LCD.
Parameters
currentFuelCol -> Column where fuel indicator is, currently.
Note
Fuel indicator will be shifted to the right of 'currentFuelCol'.
This function calls 'printToCol()' to print the fuel indicator to the next column.
The LCD display is never shifted in this function. Only the fuel indicator is shifted.
Definition at line 782 of file car_runner_rtos.c.
taskBLINK()
void taskBLINK (void * pvParameters)
Task to invert blinked value, every HIGHLIGHT_BLINK_TIME ms. This variable indicates which score should be showing in idle mode.
Increment at current showing score SCORE_SHOW_TIME rate, all the time.
Definition at line 393 of file car_runner_rtos.c.
References HIGHLIGHT_BLINK_TIME.
Referenced by main().
taskDATE()
void taskDATE (void * pvParameters)
Task to periodically get date from RTC, and overwrite queueDATE with the most recent object.
Put the most recent Date Time Strings Structure in queueDATE
Definition at line 333 of file car_runner_rtos.c.
References DATE_TIME::date, queueDATE, sprintf(), and DATE_TIME::time.
Referenced by main().
taskFUEL()
void taskFUEL (void * pvParameters)
Task to decrement fuel, every FUEL_RATE ms.
Decrement variable fuel each FUEL_RATE ms, all the time.
Definition at line 319 of file car_runner_rtos.c.
References FUEL_RATE, and semFUEL.
Referenced by main().
taskNETWORK_MANAGER()
void taskNETWORK_MANAGER (void * pvParameters)
Task to manage Network functionalities.
Definition at line 502 of file car_runner_rtos.c.
References PASS, and SSID.
Referenced by main().
taskPOINTS()
void taskPOINTS (void * pvParameters)
Task to increment points variable, every POINTS_RATE ms.
Increment variable points each POINTS_RATE ms, all the time.
Definition at line 305 of file car_runner_rtos.c.
References POINTS_RATE, and semPOINTS.
Referenced by main().
taskSCORE_COUNT()
void taskSCORE_COUNT (void * pvParameters)
Task to increment scoreCount, every SCORE_SHOW_TIME ms. This variable indicates which score should be showing in idle mode.
Increment at current showing score SCORE_SHOW_TIME rate, all the time.
Definition at line 379 of file car_runner_rtos.c.
References SCORE_NUM.
Referenced by main().
taskSTATE_MACHINE()
void taskSTATE_MACHINE (void * pvParameters)
Task to run application state machine.
Definition at line 253 of file car_runner_rtos.c.
References NAME_LENGTH.
Referenced by main().
taskUPDATE_GAME()
void taskUPDATE_GAME (void * pvParameters)
Task to run game. Waits for user input (from ADXL) and updates LCD.
Update game. This is called every GAME_RATE ms.
Definition at line 405 of file car_runner_rtos.c.
References GAME_INFO::init, queueUPDATE_GAME, and semPOINTS.
Referenced by main().
timeConfig()
void timeConfig (void)
State in which the user may configure RTC time.
Note
Use B1 and B2 to increment and decrement, respectively, the highlighted time field.
Use B3 advance to next time field.
This function never clears the LCD display.
Definition at line 1089 of file car_runner_rtos.c.
References printDateTime(), and TIME_CONFIG_FIELDS.
yesOrNo()
bool yesOrNo (void(*)(void) f)
Prompts the user with a 'Yes or No' interface, and runs the specified function if 'Yes' option is selected.
Parameters
f -> Pointer to function that shall be ran upon selection of 'Yes' option.
Returns
returns true if 'yes' was chosen, or false if 'no' was chosen.
Note
Use B1 and B2 to scroll through 'Yes' and 'No' options.
Use B3 to select highlighted option.
This function never clears the LCD display.
Definition at line 1139 of file car_runner_rtos.c.
Variable Documentation
barrier_charmap
const unsigned char barrier_charmap[]
Initial value:
= {
    0x02,
    0x0E,
    0x02,
    0x02,
    0x02,
    0x0E,
    0x02,
    0x00
}
Char map for Barrier.
Definition at line 429 of file car_runner_rtos.h.
Referenced by main().
car_back_charmap
const unsigned char car_back_charmap[]
Initial value:
= {
    0x00,
    0x06,
    0x07,
    0x06,
    0x07,
    0x06,
    0x00,
    0x00
}
Char map for Car Back.
Definition at line 387 of file car_runner_rtos.h.
Referenced by main().
car_front_charmap
const unsigned char car_front_charmap[]
Initial value:
= {
    0x00,
    0x0C,
    0x1E,
    0x02,
    0x1E,
    0x0C,
    0x00,
    0x00
}
Char map for Car Front.
Definition at line 415 of file car_runner_rtos.h.
Referenced by main().
fuel1_charmap
const unsigned char fuel1_charmap[]
Initial value:
= {
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x1f,
    0x1f
}
Char map for 1/4 fuel indicator.
Definition at line 485 of file car_runner_rtos.h.
Referenced by main().
fuel2_charmap
const unsigned char fuel2_charmap[]
Initial value:
= {
    0x00,
    0x00,
    0x00,
    0x00,
    0x1f,
    0x1f,
    0x1f,
    0x1f
}
Char map for 2/4 fuel indicator.
Definition at line 471 of file car_runner_rtos.h.
Referenced by main().
fuel3_charmap
const unsigned char fuel3_charmap[]
Initial value:
= {
    0x00,
    0x00,
    0x1f,
    0x1f,
    0x1f,
    0x1f,
    0x1f,
    0x1f
}
Char map for 3/4 fuel indicator.
Definition at line 457 of file car_runner_rtos.h.
Referenced by main().
fuel4_charmap
const unsigned char fuel4_charmap[]
Initial value:
= {
    0x1f,
    0x1f,
    0x1f,
    0x1f,
    0x1f,
    0x1f,
    0x1f,
    0x1f
}
Char map for 4/4 fuel indicator.
Definition at line 443 of file car_runner_rtos.h.
Referenced by main().
fuel_charmap
const unsigned char fuel_charmap[]
Initial value:
= {
    0x00,
    0x1C,
    0x07,
    0x0F,
    0x0F,
    0x0F,
    0x00,
    0x00
}
Char map for Fuel Galleon.
Definition at line 401 of file car_runner_rtos.h.
Referenced by main().