Car Runner: SCORE Public Functions
SCORE Public Functions
SCORE
Data Structures
struct Score
Structure to hold a score, and respective user name.
Macros
#define SCORE_NUM 3
Number of scores to be sequentially displayed in Idle Mode.
#define FLASH_SECTOR 29
Flash sector to be used.
#define MAX_SCORE 999
Maximum possible score, due to LCD fitting reasons.
#define NAME_LENGTH 11
User name maximum length.
Typedefs
typedef struct Score Score
Structure to hold a score, and respective user name.
Functions
int getScore (Score *score, int n)
Writes the requested Score to given pointer.
void sortScores (Score *scores, int size)
Sorts given array of Scores downwardly.
void saveScore (int score, char *username, int size)
If given score is one of the best 3, saves it to flash memory.
void eraseScores (void)
Erases all scores from flash memory.
Detailed Description
Macro Definition Documentation
SCORE_NUM
#define SCORE_NUM 3
Number of scores to be sequentially displayed in Idle Mode.
CONSTANTS:
Definition at line 57 of file score.h.
Typedef Documentation
Score
typedef struct Score Score
Structure to hold a score, and respective user name.
Note
This the Data Type (16 bytes) that will be stored in the Flash Memory.
Function Documentation
getScore()
int getScore (Score * score, int n)
Writes the requested Score to given pointer.
Functions:
Parameters
score -> Pointer where Score shall be written.
n -> Index of Score requested.
Definition at line 16 of file score.c.
References SCORE_NUM.
Referenced by idle().
saveScore()
void saveScore (int score, char * username, int size)
If given score is one of the best 3, saves it to flash memory.
Parameters
score -> User's score.
username -> String username.
size -> Size of string username.
Definition at line 37 of file score.c.
References FLASH_SECTOR, NAME_LENGTH, Score::score, SCORE_NUM, sortScores(), and username.
Referenced by postgame().
sortScores()
void sortScores (Score * scores, int size)
Sorts given array of Scores downwardly.
Parameters
scores -> Array of scores.
size -> Size of the array.
Definition at line 24 of file score.c.
Referenced by saveScore().