Embedded Systems Library: UART Public Functions
UART Public Functions
UART
Data Structures
struct UART_RBUF_Type
UART Ring Buffer structure.
Macros
#define UART_RBUFSIZE (1 << 11)
Ring Buffer size.
#define RBUF_MASK (UART_RBUFSIZE-1)
Ring Buffer mask.
#define RBUF_IS_FULL(head, tail) ((tail & RBUF_MASK) == ((head+1) & RBUF_MASK))
Check if Ring Buffer is full.
#define RBUF_WILL_FULL(head, tail) ((tail & RBUF_MASK) == ((head + 2) & RBUF_MASK))
Check if Ring Buffer will be full.
#define RBUF_IS_EMPTY(head, tail) ((head & RBUF_MASK) == (tail & RBUF_MASK))
Check if Ring Buffer is empty.
#define RBUF_RESET(bufidx) (bufidx = 0)
Reset Ring Buffer pointer.
#define RBUF_INCR(bufidx) (bufidx = (bufidx+1) & RBUF_MASK)
Increment Ring Buffer pointer.
#define UART_MAX_SRING_LENGTH 1024
Max length of UART String.
#define UART_TIMEOUT_MS 1000
UART default timeout in ms.
#define UART_PCLK_VAL 0x00
UART PCLK.
#define UART_DLL_MASKBIT ((uint8_t)0xFF)
UART DLL Register mask bit.
#define UART_LOAD_DLL(div) ((div) & UART_DLL_MASKBIT)
Load UART DLL with value.
#define UART_DLM_MASKBIT ((uint8_t)0xFF)
UART DLM Register mask bit.
#define UART_LOAD_DLM(div) (((div) >> 8) & UART_DLM_MASKBIT)
Load UART DLM with value.
#define UART_FDR_MASKBIT ((uint8_t)0xFF)
UART FDR Register mask bit.
#define UART_LOAD_FDR(add, mul) ((uint32_t) ((add & 0x0F) | ((mul << 4) & 0xF0)) & UART_FDR_MASKBIT)
Load UART DLM with value.
Enumerations
enum UART_PCONP_ENABLE { UART0_PCONP_ENABLE = (1 << 3), UART2_PCONP_ENABLE = (1 << 24), UART3_PCONP_ENABLE = (1 << 25) }
UART Peripheral PCONP enable.
enum UART_FCR_BITS {
UART_FCR_FIFO_EN = (1 << 0), UART_FCR_RX_RS = (1 << 1), UART_FCR_TX_RS = (1 << 2), UART_FCR_DMA_SEL = (1 << 3),
UART_FCR_TRG_LEV0 = (0 << 6)
}
UART FCR bits.
enum UART_LCR_BITS { UART_LCR_DLAB_EN = (1 << 7), UART_LCR_BREAK_EN = (1 << 6), UART_LCR_BITMASK = (0xFF) }
UART LCR bits.
enum UART_TER_BITS { UART_TER_TXEN = (1 << 7) }
UART TER bits.
enum UART_IER_BITS { UART_IER_RBRINT_EN = (1 << 0), UART_IER_THREINT_EN = (1 << 1), UART_IER_RLSINT_EN = (1 << 2), UART_IER_BITMASK = (775) }
UART IER bits.
enum UART_IIR_BITS {
UART_IIR_INTID_THRE = (1 << 1), UART_IIR_INTID_RDA = (2 << 1), UART_IIR_INTID_RLS = (3 << 1), UART_IIR_INTID_CTI = (6 << 1),
UART_IIR_INTID_MASK = (7 << 1), UART_IIR_INTSTAT_PEND = (1 << 0)
}
UART IIR bits.
enum UART_LSR_BITS {
UART_LSR_RDR = (1 << 0), UART_LSR_OE = (1 << 1), UART_LSR_PE = (1 << 2), UART_LSR_FE = (1 << 3),
UART_LSR_BI = (1 << 4), UART_LSR_THRE = (1 << 5), UART_LSR_TEMT = (1 << 6), UART_LSR_RXFE = (1 << 7)
}
UART LSR bits.
enum UART_PINFUNCTION { UART0_PINFUNCTION = (0x01), UART2_PINFUNCTION = (0x01), UART3_PINFUNCTION = (0x03) }
UART Peripheral pin function.
enum UART_PINMODE { UART0_PINMODE = (0x01), UART2_PINMODE = (0x01), UART3_PINMODE = (0x03) }
UART Peripheral pin mode.
Functions
bool UART_Init (uint32_t baud)
Initialise UART.
bool UART_IsChar (void)
Check if there is an unread character in RX FIFO.
bool UART_GetChar (unsigned char *ch)
Get character from RX FIFO.
bool UART_ReadChar (unsigned char *ch, uint32_t timeout)
Read character from RX FIFO.
void UART_WriteChar (unsigned char ch)
Write character to TX FIFO.
uint32_t UART_ReadBuffer (unsigned char *buffer, uint32_t len, uint32_t timeout)
Read array of characters from RX FIFO.
uint32_t UART_WriteBuffer (unsigned char *buffer, uint32_t len)
Write array of characters to TX FIFO.
uint32_t UART_ReadString (unsigned char *str, uint32_t timeout)
Read String from RX FIFO.
uint32_t UART_WriteString (unsigned char *str)
Write String to TX FIFO.
void UART_Printf (char *format,...)
Printf to TX FIFO.
Detailed Description
Macro Definition Documentation
RBUF_INCR
#define RBUF_INCR (bufidx) (bufidx = (bufidx+1) & RBUF_MASK)
Increment Ring Buffer pointer.
Parameters
bufidx -> pointer.
Definition at line 83 of file uart.h.
RBUF_IS_EMPTY
#define RBUF_IS_EMPTY (head, tail) ((head & RBUF_MASK) == (tail & RBUF_MASK))
Check if Ring Buffer is empty.
Parameters
head -> Which head.
tail -> Which tail.
Definition at line 71 of file uart.h.
RBUF_IS_FULL
#define RBUF_IS_FULL (head, tail) ((tail & RBUF_MASK) == ((head+1) & RBUF_MASK))
Check if Ring Buffer is full.
Parameters
head -> Which head.
tail -> Which tail.
Definition at line 57 of file uart.h.
RBUF_MASK
#define RBUF_MASK (UART_RBUFSIZE-1)
Ring Buffer mask.
Definition at line 50 of file uart.h.
RBUF_RESET
#define RBUF_RESET (bufidx) (bufidx = 0)
Reset Ring Buffer pointer.
Parameters
bufidx -> pointer.
Definition at line 77 of file uart.h.
RBUF_WILL_FULL
#define RBUF_WILL_FULL (head, tail) ((tail & RBUF_MASK) == ((head + 2) & RBUF_MASK))
Check if Ring Buffer will be full.
Parameters
head -> Which head.
tail -> Which tail.
Definition at line 64 of file uart.h.
UART_DLL_MASKBIT
#define UART_DLL_MASKBIT ((uint8_t)0xFF)
UART DLL Register mask bit.
Definition at line 114 of file uart.h.
UART_DLM_MASKBIT
#define UART_DLM_MASKBIT ((uint8_t)0xFF)
UART DLM Register mask bit.
Definition at line 125 of file uart.h.
UART_FDR_MASKBIT
#define UART_FDR_MASKBIT ((uint8_t)0xFF)
UART FDR Register mask bit.
Definition at line 136 of file uart.h.
UART_LOAD_DLL
#define UART_LOAD_DLL (div) ((div) & UART_DLL_MASKBIT)
Load UART DLL with value.
Parameters
div -> Value.
Definition at line 120 of file uart.h.
UART_LOAD_DLM
#define UART_LOAD_DLM (div) (((div) >> 8) & UART_DLM_MASKBIT)
Load UART DLM with value.
Parameters
div -> Value.
Definition at line 131 of file uart.h.
UART_LOAD_FDR
#define UART_LOAD_FDR (add, mul) ((uint32_t) ((add & 0x0F) | ((mul << 4) & 0xF0)) & UART_FDR_MASKBIT)
Load UART DLM with value.
Parameters
add -> Add value.
mul -> Mul value.
Definition at line 143 of file uart.h.
UART_MAX_SRING_LENGTH
#define UART_MAX_SRING_LENGTH 1024
Max length of UART String.
Definition at line 99 of file uart.h.
UART_PCLK_VAL
#define UART_PCLK_VAL 0x00
UART PCLK.
Definition at line 109 of file uart.h.
UART_RBUFSIZE
#define UART_RBUFSIZE (1 << 11)
Ring Buffer size.
Definition at line 45 of file uart.h.
UART_TIMEOUT_MS
#define UART_TIMEOUT_MS 1000
UART default timeout in ms.
Definition at line 104 of file uart.h.
Enumeration Type Documentation
UART_FCR_BITS
enum UART_FCR_BITS
UART FCR bits.
Enumerator
UART_FCR_FIFO_EN
Enable FIFO.
UART_FCR_RX_RS
Clear all bytes in RX FIFO.
UART_FCR_TX_RS
Clear all bytes in TX FIFO.
UART_FCR_DMA_SEL
Select DMA Mode (if UART_FCR_FIFO_EN is set).
UART_FCR_TRG_LEV0
Trigger RX level 0.
Definition at line 169 of file uart.h.
UART_IER_BITS
enum UART_IER_BITS
UART IER bits.
Enumerator
UART_IER_RBRINT_EN
RBR Interrupt Enable.
UART_IER_THREINT_EN
THRE Interrupt Enable.
UART_IER_RLSINT_EN
RX Line Status Interrupt Enable.
UART_IER_BITMASK
Definition at line 196 of file uart.h.
UART_IIR_BITS
enum UART_IIR_BITS
UART IIR bits.
Enumerator
UART_IIR_INTID_THRE
THRE Interrupt.
UART_IIR_INTID_RDA
Receive Data Available.
UART_IIR_INTID_RLS
Receive Line Status
UART_IIR_INTID_CTI
Character Time-out Indicator.
UART_IIR_INTID_MASK
Mask for Interrupt Identification.
UART_IIR_INTSTAT_PEND
Definition at line 206 of file uart.h.
UART_LCR_BITS
enum UART_LCR_BITS
UART LCR bits.
Enumerator
UART_LCR_DLAB_EN
Enable Divisor Latch Access Bit.
UART_LCR_BREAK_EN
Break Control.
UART_LCR_BITMASK
Definition at line 180 of file uart.h.
UART_LSR_BITS
enum UART_LSR_BITS
UART LSR bits.
Enumerator
UART_LSR_RDR
Receiver Data Ready.
UART_LSR_OE
Overrun Error.
UART_LSR_PE
Parity Error.
UART_LSR_FE
Framing Error.
UART_LSR_BI
Break Interrupt.
UART_LSR_THRE
Transmitter Holding Register Empty.
UART_LSR_TEMT
Transmitter Empty.
UART_LSR_RXFE
Error in RX FIFO.
Definition at line 218 of file uart.h.
UART_PCONP_ENABLE
enum UART_PCONP_ENABLE
UART Peripheral PCONP enable.
Enumerator
UART0_PCONP_ENABLE
Power/clock control bit for UART0.
UART2_PCONP_ENABLE
Power/clock control bit for UART2.
UART3_PCONP_ENABLE
Power/clock control bit for UART3.
Definition at line 160 of file uart.h.
UART_PINFUNCTION
enum UART_PINFUNCTION
UART Peripheral pin function.
Enumerator
UART0_PINFUNCTION
Pin function for UART0.
UART2_PINFUNCTION
Pin function for UART2.
UART3_PINFUNCTION
Pin function for UART3.
Definition at line 232 of file uart.h.
UART_PINMODE
enum UART_PINMODE
UART Peripheral pin mode.
Enumerator
UART0_PINMODE
Pin mode for UART0.
UART2_PINMODE
Pin mode for UART2.
UART3_PINMODE
Pin mode for UART3.
Definition at line 241 of file uart.h.
UART_TER_BITS
enum UART_TER_BITS
UART TER bits.
Enumerator
UART_TER_TXEN
Output THR to TXD.
Definition at line 189 of file uart.h.
Function Documentation
UART_GetChar()
bool UART_GetChar (unsigned char * ch)
Get character from RX FIFO.
Parameters
ch -> Where character shall be written to.
Returns
True if there was an unread character in RX, false otherwise.
Note
This function is non-blocking.
Definition at line 351 of file uart.c.
Referenced by ESP_GetChar().
UART_Init()
bool UART_Init (uint32_t baud)
Initialise UART.
Note
This function must be called prior to other UART functions.
Parameters
baud -> Baud rate (max: 115200)
Note
If baud is passed as 0, default 9600 will be set.
Returns
True if successful, false otherwise.
Definition at line 278 of file uart.c.
Referenced by ESP_Init().
UART_IsChar()
bool UART_IsChar (void)
Check if there is an unread character in RX FIFO.
Returns
True if there's an unread character in RX, false otherwise.
Definition at line 343 of file uart.c.
UART_Printf()
void UART_Printf (char * format, ...)
Printf to TX FIFO.
Parameters
format -> Format String.
... -> Printf paramters.
Definition at line 441 of file uart.c.
References UART_MAX_SRING_LENGTH, and UART_WriteString().
UART_ReadBuffer()
uint32_t UART_ReadBuffer (unsigned char * buffer, uint32_t len, uint32_t timeout)
Read array of characters from RX FIFO.
Parameters
buffer -> Where buffer shall be written to.
len -> Buffer length expected.
timeout -> Maximum time in ms the function should block, waiting for data to arrive.
Returns
Number of characters read.
Note
This function is blocking (until timeout is met).
Definition at line 389 of file uart.c.
UART_ReadChar()
bool UART_ReadChar (unsigned char * ch, uint32_t timeout)
Read character from RX FIFO.
Parameters
ch -> Where character shall be written to.
timeout -> Maximum time in ms the function should block, waiting for data to arrive.
Returns
True if a character was read, false if timeout was met.
Note
This function is blocking (until timeout is met).
Definition at line 347 of file uart.c.
Referenced by ESP_ReadChar().
UART_ReadString()
uint32_t UART_ReadString (unsigned char * str, uint32_t timeout)
Read String from RX FIFO.
Parameters
str -> Where String shall be written to.
timeout -> Maximum time in ms the function should block, waiting for data to arrive.
Returns
Number of characters read.
Note
This function is blocking (until timeout is met).
Definition at line 412 of file uart.c.
Referenced by ESP_ReadString().
UART_WriteBuffer()
uint32_t UART_WriteBuffer (unsigned char * buffer, uint32_t len)
Write array of characters to TX FIFO.
Parameters
buffer -> Array to write.
len -> Buffer length.
Returns
Number of characters written.
Definition at line 366 of file uart.c.
UART_WriteChar()
void UART_WriteChar (unsigned char ch)
Write character to TX FIFO.
Parameters
ch -> The character to write.
Definition at line 355 of file uart.c.
Referenced by ESP_WriteChar().
UART_WriteString()
uint32_t UART_WriteString (unsigned char * str)
Write String to TX FIFO.
Parameters
str -> String to write.
Returns
Number of characters written.
Definition at line 408 of file uart.c.
Referenced by ESP_WriteString(), and UART_Printf().