Embedded Systems Library: NTP Public Functions
NTP Public Functions
NTP
Data Structures
struct NTP_PACKET
NTP packet structure for NTP transmitting and receiving.
Macros
#define CONNECTION_KEEPALIVE_S 60UL
Keep alive parameter.
#define MQTT_ADDRESS "iot-se2021.ddns.net"
MQTT Address for score publishing.
#define MQTT_PORT 1883
MQTT Port for score publishing.
#define MQTT_DEVICE_TOKEN "SE2-BEST-RECORDS"
MQTT Device Token for score publishing.
#define GROUP_ID 9
Group Identification for score publishing.
#define TASK_SCORE_PUBLISHER_STACK_SIZE configMINIMAL_STACK_SIZE*2
Score Publisher Task Stack Size.
#define TASK_SCORE_PUBLISHER_PRIORITY tskIDLE_PRIORITY + 1
Score Publisher Task Priority.
Enumerations
enum NEWTORK_STATE {
NETWORK_STATE_IDLE = 0, NETWORK_STATE_INIT = 1, NETWORK_STATE_CONNECT = 2, NETWORK_STATE_WAIT_CONNECT = 3,
NETWORK_STATE_PUBLISH = 4, NETWORK_STATE_DISCONNECT = 5
}
Network State Machine states.
Functions
bool NETWORK_Init (void)
Initialise Network API.
bool NETWORK_ConnectToAP (char *ssid, char *password)
Connect to Access Point.
uint32_t NETWORK_GetSeconds (void)
Get current time seconds.
void NETWORK_PublishScore (int scoreSend)
Publish a score.
Detailed Description
Macro Definition Documentation
CONNECTION_KEEPALIVE_S
#define CONNECTION_KEEPALIVE_S 60UL
Keep alive parameter.
Definition at line 80 of file network.h.
GROUP_ID
#define GROUP_ID 9
Group Identification for score publishing.
Definition at line 100 of file network.h.
MQTT_ADDRESS
#define MQTT_ADDRESS "iot-se2021.ddns.net"
MQTT Address for score publishing.
Definition at line 85 of file network.h.
MQTT_DEVICE_TOKEN
#define MQTT_DEVICE_TOKEN "SE2-BEST-RECORDS"
MQTT Device Token for score publishing.
Definition at line 95 of file network.h.
MQTT_PORT
#define MQTT_PORT 1883
MQTT Port for score publishing.
Definition at line 90 of file network.h.
TASK_SCORE_PUBLISHER_PRIORITY
#define TASK_SCORE_PUBLISHER_PRIORITY tskIDLE_PRIORITY + 1
Score Publisher Task Priority.
Definition at line 110 of file network.h.
TASK_SCORE_PUBLISHER_STACK_SIZE
#define TASK_SCORE_PUBLISHER_STACK_SIZE configMINIMAL_STACK_SIZE*2
Score Publisher Task Stack Size.
Definition at line 105 of file network.h.
Enumeration Type Documentation
NEWTORK_STATE
enum NEWTORK_STATE
Network State Machine states.
Enumerator
NETWORK_STATE_IDLE
NETWORK_STATE_INIT
NETWORK_STATE_CONNECT
NETWORK_STATE_WAIT_CONNECT
NETWORK_STATE_PUBLISH
NETWORK_STATE_DISCONNECT
Definition at line 115 of file network.h.
Function Documentation
NETWORK_ConnectToAP()
bool NETWORK_ConnectToAP (char * ssid, char * password)
Connect to Access Point.
Parameters
ssid -> SSID of Access Point.
password -> Password of Access Point.
Returns
True if successful, false otherwise.
Definition at line 51 of file network.c.
References ESP_BOTH, ESP_ConfigureConnection(), ESP_Connect(), ESP_EnableEcho(), ESP_Init(), ESP_Mode(), and ESP_SINGLE.
NETWORK_GetSeconds()
uint32_t NETWORK_GetSeconds (void)
Get current time seconds.
Returns
Seconds since 01/01/1970 00:00:00.
Set the first byte's bits to 0001 1011. li = 0, vn = 3, and mode = 3. The rest will be left set to zero.
Definition at line 75 of file network.c.
References ESP_Close(), ESP_ReceiveData(), ESP_SendData(), ESP_Start(), ESP_UDP, NTP_PACKET::li_vn_mode, NTP_PACKET::poll, NTP_PACKET::precision, and NTP_PACKET::stratum.
NETWORK_Init()
bool NETWORK_Init (void)
Initialise Network API.
Returns
True if successful, false otherwise.
Note
Must be called prior to other NETWORK functions.
Definition at line 37 of file network.c.
References NETWORK_ScorePublisherTask(), TASK_SCORE_PUBLISHER_PRIORITY, and TASK_SCORE_PUBLISHER_STACK_SIZE.
NETWORK_PublishScore()
void NETWORK_PublishScore (int scoreSend)
Publish a score.
Parameters
scoreSend -> Score to publish.
Definition at line 134 of file network.c.