Embedded Systems Library: RTC Public Functions
RTC Public Functions
RTC
Macros
#define RTC_PCONP_ENABLE (1 << 9)
Enable PCONP bit for RTC.
#define RTC_ENABLE 0x01
Enable RTC counters.
#define RTC_DISABLE 0x00
Disable RTC counters.
#define RTC_IL_BIT 0x01
RTC interrupt Location bit.
Enumerations
enum RTC_INTERRUPT_FIELD {
INONE = 0x00, ISEC = 0x01, IMIN = 0x02, IHOUR = 0x04,
IDOM = 0x08, IDOW = 0x10, IDOY = 0x20, IMONTH = 0x40,
IYEAR = 0x080
}
Field that will interrupt.
enum RTC_TIME_FIELD {
NONE, YEAR, MONTH, DOM,
DOW, HOUR, MIN, SEC
}
Time field.
Functions
void RTC_Init (time_t seconds)
Initialises the RTC API, with the desired time.
void RTC_GetValue (struct tm *dateTime)
Sends current RTC time to desired location.
void RTC_SetValue (struct tm *dateTime)
Sets RTC time value with the desired time.
time_t RTC_GetSeconds (void)
Gets the RTC time value.
void RTC_SetSeconds (time_t seconds)
Sets RTC time value with the desired seconds, since Epoh (01/01/1970).
void RTC_Enable (void)
Enable RTC counters.
void RTC_Disable (void)
Disable RTC counters.
void RTC_IncrementField (RTC_TIME_FIELD field)
Increment field specified.
void RTC_DecrementField (RTC_TIME_FIELD field)
Decrement field specified.
Detailed Description
Macro Definition Documentation
RTC_DISABLE
#define RTC_DISABLE 0x00
Disable RTC counters.
Definition at line 52 of file rtc.h.
RTC_ENABLE
#define RTC_ENABLE 0x01
Enable RTC counters.
Definition at line 47 of file rtc.h.
RTC_IL_BIT
#define RTC_IL_BIT 0x01
RTC interrupt Location bit.
Definition at line 57 of file rtc.h.
RTC_PCONP_ENABLE
#define RTC_PCONP_ENABLE (1 << 9)
Enable PCONP bit for RTC.
Definition at line 42 of file rtc.h.
Enumeration Type Documentation
RTC_INTERRUPT_FIELD
enum RTC_INTERRUPT_FIELD
Field that will interrupt.
Enumerator
INONE
to never interrupt.
ISEC
to interrupt every second.
IMIN
to interrupt every minute.
IHOUR
to interrupt every hour.
IDOM
to interrupt every day of month.
IDOW
to interrupt every day of week.
IDOY
to interrupt every day of year.
IMONTH
to interrupt every month.
IYEAR
to interrupt every year.
Definition at line 62 of file rtc.h.
RTC_TIME_FIELD
enum RTC_TIME_FIELD
Time field.
Enumerator
NONE
None.
YEAR
Year field.
MONTH
Month field.
DOM
Day of Month field.
DOW
Day of Week field.
HOUR
Hour field.
MIN
Minute field.
SEC
Second field.
Definition at line 78 of file rtc.h.
Function Documentation
RTC_DecrementField()
void RTC_DecrementField (RTC_TIME_FIELD field)
Decrement field specified.
Note
Decrementing the lowest possible value, will set it back to the highest value.
Definition at line 111 of file rtc.c.
References DOM, MONTH, and YEAR.
RTC_Disable()
void RTC_Disable (void)
Disable RTC counters.
Note
You can enable it back using RTC_Enable().
Definition at line 69 of file rtc.c.
References RTC_DISABLE.
RTC_Enable()
void RTC_Enable (void)
Enable RTC counters.
Definition at line 65 of file rtc.c.
References RTC_ENABLE.
Referenced by RTC_Init().
RTC_GetSeconds()
time_t RTC_GetSeconds (void)
Gets the RTC time value.
Returns
Seconds since Epoh (01/01/1970).
Definition at line 53 of file rtc.c.
References RTC_GetValue().
RTC_GetValue()
void RTC_GetValue (struct tm * dateTime)
Sends current RTC time to desired location.
Parameters
dateTime -> Desired location.
Definition at line 29 of file rtc.c.
Referenced by RTC_GetSeconds().
RTC_IncrementField()
void RTC_IncrementField (RTC_TIME_FIELD field)
Increment field specified.
Note
Incrementing the highest possible value, will set it back to the lowest value.
Definition at line 73 of file rtc.c.
References DOM, MONTH, and YEAR.
RTC_Init()
void RTC_Init (time_t seconds)
Initialises the RTC API, with the desired time.
Parameters
seconds -> Seconds since 01/01/1970.
Note
If parameter type is INONE, no handler is needed. Only the first 2 parameters will be read.
Only the first 3 parameters can be read. Any other parameters will be ignored.
This function must be called prior to any other RTC functions.
Definition at line 17 of file rtc.c.
References RTC_DISABLE, RTC_Enable(), RTC_PCONP_ENABLE, and RTC_SetSeconds().
RTC_SetSeconds()
void RTC_SetSeconds (time_t seconds)
Sets RTC time value with the desired seconds, since Epoh (01/01/1970).
Parameters
seconds -> Desired seconds.
Definition at line 60 of file rtc.c.
References RTC_SetValue().
Referenced by RTC_Init().
RTC_SetValue()
void RTC_SetValue (struct tm * dateTime)
Sets RTC time value with the desired time.
Parameters
dateTime -> Desired time.
Definition at line 41 of file rtc.c.
Referenced by RTC_SetSeconds().